#!/bin/bash

# Set paths
SloKJVepubPath=/home/pc/Dokumenti/epub
osis2usfm=/home/pc/Dokumenti/osis2usfm
SloKJV_Github=/home/pc/Dokumenti/GitHub/SloKJV
SloKJV=/home/pc/Dokumenti/osis2usfm/SloKJV/release/SloKJV_
format=US_Trade

#======= zberi velikost PDF verzije SloKJV =============
echo "   Izberi velikost PDF verzije SloKJV"
PS3='Izberi velikost PDF verzije SloKJV: '
options=("A4" "US_Trade" "A5" "A5_NZ" "Izhod")
select opt in "${options[@]}"
do
    case $opt in
        "A4")
            echo "   Izbral si A4."
            format=A4
            break
            ;;
        "US_Trade")
            echo "   Izbral si US_Trade."
            format=US_Trade
            break
            ;;
        "A5")
            echo "   Izbral si A5."
            format=A5
            break
            ;;
        "A5_NZ")
            echo "   Izbral si A5_NZ."
            format=A5_NZ
            break
            ;;
        "Izhod")
            echo "   Izbral si $REPLY kar je $opt"
            exit
            ;;
        *) echo "Napacna izbira $REPLY";;
    esac
done
#===================================================

# Kreira mapo z izbrano velikostjo SloKJV PDF datoteke.
mkdir $SloKJV_Github/PTXprint/osis2usfm/SloKJV/release/SloKJV_$format  2>/dev/null

# Naredi simbolicen link iz Github na mapo osis2usfm (samo prvic)
ln -s $SloKJV_Github/PTXprint/osis2usfm/run_osis2usfm $osis2usfm
ln -s $SloKJV_Github/PTXprint/osis2usfm/osis2usfm.py $osis2usfm
ln -s $SloKJV_Github/PTXprint/osis2usfm/SloKJV/ $osis2usfm

#================ PTXPrint nadgradi na zadnjo verzijo? ====================
echo " "
echo "   Ali se PTXPrint nadgradi na zadnjo verzijo?"
echo " "
PS4='   Izberi: '
options_ver=("Ne" "Nadgradi" "Izhod")
 select opt_ver in "${options_ver[@]}"
 do
     case $opt_ver in
         "Ne")
             echo " "
             echo "   Pa drugic nadgradnja PTXprint...."
             echo " "
             break
             ;;
         "Nadgradi")
             echo " "
             echo "   Izbral si nadgraditev."
             echo " "
             echo "     Ubuntu package ptxprint update ..."
             echo " "
                 sudo add-apt-repository ppa:silnrsi/ptxprint
                 sudo apt update
                 sudo apt install python3-ptxprint
             break
             ;;
         "Izhod")
             echo " "
             echo "Izbral si $REPLY kar je $opt_ver"
             echo " "
             exit
             ;;
         *) echo "Napacna izbira $REPLY";;
     esac
 done
#==========================================================================


# Potegne iz Githuba (po zelji izklopi ko ni interneta)
#https_proxy=http://proxy.gov.si:80/
#wget --no-proxy https://github.com/msavli/SloKJV/raw/master/SloKJV_sword.xml -O /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml


#============ Pozene GITHUB Desktop? ========================
echo " "
echo "   Pozene GITHUB Desktop?"
echo " "
PS5='   Izberi: '
options_ver=("Pozene" "Ne" "Izhod")
select opt_ver in "${options_ver[@]}"
do
      case $opt_ver in
          "Pozene")
              echo " "
              echo "   Izbral si nadgraditev."
              echo " "
              echo "     Sinhronizacija z Githubom ..."
              echo " "
                #================================================================================
                echo -E "  Ocisti mape zacasnih datotek..."
                find $SloKJV_Github/PTXprint -name '*.usfm' -exec rm {} \;        >/dev/null 2>&1
                find $SloKJV_Github/PTXprint -name 'local'  -exec rm -rf {} \;    >/dev/null 2>&1
                #================================================================================
              /usr/bin/github-desktop
              break
              ;;
          "Ne")
              echo " "
              echo "   Pa drugic sinhronizacija z Githubom."
              echo " "
              break
             ;;
          "Izhod")
              echo " "
              echo "   Izbral si $REPLY kar je $opt_ver"
              echo " "
              exit
             ;;
          *) echo "Napacna izbira $REPLY";;
     esac
done
#==========================================================================


cd $osis2usfm

# Potegne iz lokanega Githuba (hitreje)
cp /home/pc/Dokumenti/GitHub/SloKJV/SloKJV_sword.xml  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
	# ls -al /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
	# sleep 2s # Caka 2 sekundi

# Naredi mapo release in mapo projekta
mkdir $osis2usfm/SloKJV/release                >/dev/null 2>&1
mkdir $osis2usfm/SloKJV/release/SloKJV_$format >/dev/null 2>&1

# Prestavi se v mapo   osis2usfm=/home/pc/Dokumenti/osis2usfm
cd $osis2usfm                                  >/dev/null 2>&1



# =============================
echo -E "   --==    Uredi odstavke                                                "
echo -E "   --==    <milestone type=\"x-p\" marker=\"¶ \"/>                       "
echo -E "   --==    <milestone type=\"x-p\" subType=\"x-added\" marker=\"¶\"/>    "
echo -E "   --==   \p                                                             "
sed -i "s|<milestone type=\"x-p\" marker=\"¶ \"/>| \x5cp |g"                      /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|<milestone type=\"x-p\" subType=\"x-added\" marker=\"¶\"/>| \x5cp |g"   /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "milestone"

#echo -E "   --==    Najprej je treba vrstico z besedilom prestaviti eno visje k stevilki vrstice - zato da bom note reference lahko uredil  "
 #
 #  sed ':a;N;$!ba;s/\n/ /g' file
 #
 #    :a create a label 'a'
 #    N append the next line to the pattern space
 #    $! if not the last line, ba branch (go to) label 'a'
 #    s substitute, /\n/ regex for new line, / / by a space, /g global match (as many times as it can)
 #                                potegne gor vrstivce k stevilki verza
sed -i ':a;N;$!ba;s/\">\n/\"> /g'                                                   /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
 #                      "> \p     se vrstice z znakom za odstavek potegne gor
sed -i ':a;N;$!ba;s/\"> \\p \n/"> \x5cp /g'                                         /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "<verse osisID"
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "<verse osisID=\"Isa.49.5\""



#     Psalmi:       potegne gor vrstice k stevilki verza
#          </title><verse osisID=\"Ps.
echo -E "   --==    Uredi odstavke v Psalmih                                       "
echo -E "   --==       Zamenja   \n          </title><verse osisID=\"Ps               </title>\n              <verse osisID=\"Ps "
#    Dodal Y ker mi to daje znak za konec naslova psalma, kasneje spodaj odstranim.
sed -i ':a;N;$!ba;s|\n          </title><verse osisID=\"Ps|Y</title>\n                        <verse osisID=\"Ps|g' /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

#   Odstrani dva presledka pred psalmi ki imajo naslov pslama        <verse osisID=\"Ps
#     zato da datoteka lepse in enotno zgleda
sed -i "s|                        <verse osisID=\"|                      <verse osisID=\"|g"            /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Odstrani 12 presledokov pred               </verse></chapter><chapter osisID=
sed -i "s|              </verse></chapter><chapter osisID=|  </verse></chapter><chapter osisID=|g"      /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml



# ======= REFERENCE ===============
echo -E "                                                                             "
echo -E "   --==   Cross reference element begin      mora biti pred <note...         "
echo -E "         <note type=\"crossReference\">                                      "
echo -E "            <reference osisRef=\"Ps.33.6\">Ps 33:6</reference>;              "
echo -E "            <reference osisRef=\"Ps.136.5\">Ps 136:5</reference>;            "
echo -E "            <reference osisRef=\"Acts.14.15\">Apd 14:15</reference>;         "
echo -E "            <reference osisRef=\"Acts.17.24\">Apd 17:24</reference>;         "
echo -E "            <reference osisRef=\"Heb.11.3\">Heb 11:3</reference>             "
echo -E "         </note>                                                             "
echo -E "   --==   \x - \xr:        \x*                                               "
echo -E "                                                                             "
#            Najprej zmanjsamo <reference ....    reference>   samo tam kjer je vec referenc s podpicjem
#                    <reference osisRef="Isa.65.17">Iz 65:17</reference>

# Najprej samo zmanjsa reference -> ;XYX
sed -i "s|</reference>; <reference osisRef=|;XYX|g"            /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

# tukaj glede druge po vrsti in naslednje reference v enem note zapisu in spremeni vmesne dele v podpicja
#         ;XYX"Acts.17.24">   zamenja ->  ;
sed -i "s|;XYX\"[^\"]*\">|; |g"                                /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

#   <reference osisRef="Ps.33.6">   zamenjam z nic to je prva opomba angleski del da ostane samo slovenski del
sed -i "s|<reference osisRef=\"[^\"]*\">|; |g"                 /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

# Odstrani se  </reference></note> in zamenja ->  \x*
sed -i "s|</reference></note>|\x5cx*|g"                      /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

# Zamenja <note type="crossReference">;   ->   \x - \xo:  PPP
sed -i "s|<note type=\"crossReference\">;|\x5cx + \x5cxo \x5creference : \x5cxt |g" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Tu zgoraj sem odstranil  + \x5cfxt

#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "<verse osisID=\"Gen.1.1\""
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "<reference"
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "reference>"
#head -30 /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml


# ======= VGNEZDEN GOSPOD ===============
echo -E "                                                      "
echo -E "   --==      Če je vgnezden recimo v opombi pa je     "
echo -E "   --==      <divineName>Gospod</divineName>          "
echo -E "   --==      \+nd Gospod \+nd*                        "
# V  je 1Sam.12.14 en tak vgnezden Gospod primer - toda v dveh referencah
# Za vsak slucaj dodam se tretjo  pojavitev GOSPOD v opombi - zato tri vrstice
#         <note type="\study\">

# bla1 <d>G</d> bla2 <d>G</d><note t="s"><d>G</d>…: bla3. <d>G</d> bla4.</note> bla5 <note t="s">bla6…: bla7. bla8 <d>G</d>, bla9.</note> bla10 <d>G</d> bla11.


sed -i "s|<note t=\"s\">\([^.]*\)<d>\([^.]*\)</note>|<note t=\"s\">\1<dX>\2</note>|g"    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|<note t=\"s\">\([^.]*\)</d>\([^.]*\)</note>|<note t=\"s\">\1</dY>\2</note>|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

# Zamenja  <dX>  z   \+nd
#    in    </dY> z   \+nd*
#sed -i "s|<dX>|\x5+nd |g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<dY>|\x5+nd*|g" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

# Ali to res dela na tej vrstici 1Sam.12.14
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "<verse osisID=\"1Sam.12.14\""




# ======= OPOMBE ===============
# Toda najprej mora biti reseno gornje vgnezdenje Gospoda
echo -E " "
echo -E "   --==    <note type=\"study\">  \</note> "
echo -E "   --==   \f opomba \f*"
sed -i "s|<note type=\"study\">|\x5cf + \x5cfr \x5creference : \x5cft |g"                              /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|</note>|\x5cf*|g"                                                     /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "<note>"
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "</note>"




# ======= DODANE BESEDE ITALIC ===============
echo -E " "
echo -E "   --==    <transChange type=\"added\">je bila</transChange>     "
echo -E "   --==   \add was\add*     "
sed -i "s|<transChange type=\"added\">|\x5cadd |g"                               /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|</transChange>|\x5cadd*|g"                                             /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "transChange"
# =======================================================

# ======= DODANE BESEDE ITALIC VGNEZDEN ===============================================
echo -E "   --==     če je vgnezden v opombo              "
echo -E "   --==   \+add    \+add*                        "
# Med Jezusovim govorjenjem so italic besede, ki morajo biti vgnezdene
#  <q who=\"Jesus\" marker=\"\">„Jaz, Davidov \+add in\+add* svetla ter jutranja zvezda.“</q>
# cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "svetla ter jutranja zvezda"
# </verse><verse osisID="Rev.22.16"> \p <q who="Jesus" marker="">„Jaz, Jezus,  \add in\add* zvezda.“</q>
# Primer ce je v tej vrstici pika. Naprej isce \add*     in doda +
# 12x pa zoto ce je 5 italic opomb v Jezus vrstici in je v njej ena pika
# Odstranil ker tega ni v usfm 
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)[.]\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1.\2\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

# Ce v vrstici ni pike.
# 12x pa zoto ce je v njej 5 italic opomb v Jezus vrstici brez vmesne  pika
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<q who=\"Jesus\" marker=\"\">\([^.]*\)\\\\add|<q who=\"Jesus\" marker=\"\">\1\x5c+add|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

# Sedaj pa se izjeme ki gornjih 24 vrstic ne upostevajo.
#    Oh, \add vi\add* hinavci, lahko razpoznavate obličje neba, toda ne morete \add razpoznati\add* znamenj
#    Oh, \\\\add vi\\\\add* hinavci, lahko razpoznavate obličje neba, toda ne morete \\\\add razpoznati\\\\add* znamenj
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "lahko razpoznavate obli"
#sed -i "s|\\\\add vi\\\\add\* hinavci|\x5c+add vi\x5c+add\* hinavci|g" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|\\\\add razpoznati\\\\add\* znamenj|\x5c+add razpoznati\x5c+add\* znamenj|g" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "lahko razpoznavate obli"

# koliko bolj \add bodo imenovali\add* te iz njegove
# koliko bolj \\\\add bodo imenovali\\\\add\* te iz njegove
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "te iz njegove družine"
#sed -i "s|koliko bolj \\\\add bodo imenovali\\\\add\* te iz njegove|koliko bolj \x5c+add bodo imenovali\x5c+add\* te iz njegove|g" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "te iz njegove družine"

#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "Niti se ne dajte imenovati učitelji"
#sed -i "s|\\\\add celó\\\\add\* Kristus|\x5c+add celó\x5c+add\* Kristus|g"    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "Niti se ne dajte imenovati učitelji"

#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "postave, sodbo, usmiljenje in vero"
#sed -i "s|pomembnejše \\\\add zadeve\\\\add\* iz|pomembnejše \x5c+add zadeve\x5c+add* iz|g"   /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "postave, sodbo, usmiljenje in vero"



# ======= DIVINE NAME GOSPOD ===============
# Zamenja  po vsem besedilu - toda najprej mora rešiti Vgnezdnje Gospod zgoraj
echo -E " "
echo -E "   --==      <divineName>Gospod</divineName>     "
echo -E "   --==   \nd  LORD  \nd*   "
sed -i "s|<divineName>|\x5cnd |g"            /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|</divineName>|\x5cnd*|g"          /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "<divine>"
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "</divine>"

# Spet vgnezdene izjeme
#  \nd Gospod\nd* je rekel mojemu Gospodu
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "na mojo desnico, dokler ne storim tvojih sovražnikov"
sed -i "s|\\\\nd Gospod\\\\nd\* je rekel mojemu Gospodu|\x5c+nd Gospod\x5c+nd\* je rekel mojemu Gospodu|g"     /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "na mojo desnico, dokler ne storim tvojih sovražnikov"

#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "nam bodo stvari nadnaravno dodane od Boga"
sed -i "s|\\\\add tvoje oko\\\\add\* hudobno, \\\\add je\\\\add\*|\x5c+add tvoje oko\x5c+add\* hudobno, \x5c+add je\x5c+add\*|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "nam bodo stvari nadnaravno dodane od Boga"

#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "te stvari se morajo najprej zgoditi"
sed -i "s|konec \\\\add še\\\\add\* ni v kratkem|konec \x5c+add še\x5c+add\* ni v kratkem|g"     /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "te stvari se morajo najprej zgoditi"

#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "bom ven in bom lažniv duh v ustih"
sed -i "s|\\\\add \\\\nd Gospod\\\\nd\*\\\\add\*|\x5c+add \x5c+nd Gospod\x5c+nd\*\x5c+add\*|g"     /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "bom ven in bom lažniv duh v ustih"
# ===============================================================


# ============TOC Menda uredi program za konverzijo===============
	#echo -E " "
	#echo -E "   --==      <title type=\"main\" short=\"Geneza\">Prva Mojzesova knjiga, imenovana Geneza</title>   "
	#echo -E "   --==   \mt1    "

	#echo -E " "
	#echo -E "   --==      <title type=\"main\" short=\"Geneza\">Prva Mojzesova knjiga, imenovana Geneza</title>    "
	#echo -E "   --==   \toc1 The First Book of Moses, called Genesis     "
	#echo -E "   --==   \toc2 Genesis    "
	#sed -i "s|<title type=\"main\" short=\"\([^.]*\)\">\([^.]*\)</title>| \x5ctoc2 \1 \x5ctoc1 \2 |g"   /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
	#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "toc1"
	#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "toc2"


	#echo -E " "
	#echo -E "   --==     <div type=\"book\" osisID=\"Gen\">     "
	#echo -E "   --==   \toc3 Gen     "
	#sed -i "s|<div type=\"book\" osisID=\"\([^.]*\)\">| \x5ctoc3 \1 |g"   /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
	#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "toc3"
# ============To menda uredi program za konverzijo===============


# ================== Hebrejske besede v Psalmih ==================
echo -E "   --==              <verse osisID=\"Ps.119.1\"> <title type=\"acrostic\" canonical=\"true\"><foreign n=\"א\">ALEF א</foreign> </title>   "
echo -E "   --==             \qa "
# Moram pa ALEF dati pred verse
# Zato toliko vrstic, ker imajo ene spredaj </verse> in druge imajo vmes \p.  Zato se dvakrat ponovijo.
sed -i "s|                      <verse osisID=\"\([^.]*\).\([^.]*\).\([^.]*\)\"> <title type=\"acrostic\" canonical=\"true\"><foreign n=\"\([^.]*\)\">\([^.]*\)</foreign> </title>|\x5cqa \5 \n\                      <verse osisID=\"\1.\2.\3\"> |g" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|                      <verse osisID=\"\([^.]*\).\([^.]*\).\([^.]*\)\"> \\\p <title type=\"acrostic\" canonical=\"true\"><foreign n=\"\([^.]*\)\">\([^.]*\)</foreign> </title>|\x5cqa \5 \n\                      <verse osisID=\"\1.\2.\3\"> \x5cp |g" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|              </verse><verse osisID=\"\([^.]*\).\([^.]*\).\([^.]*\)\"> <title type=\"acrostic\" canonical=\"true\"><foreign n=\"\([^.]*\)\">\([^.]*\)</foreign> </title>|\x5cqa \5 \n\              </verse><verse osisID=\"\1.\2.\3\"> |g" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|              </verse><verse osisID=\"\([^.]*\).\([^.]*\).\([^.]*\)\"> \\\p <title type=\"acrostic\" canonical=\"true\"><foreign n=\"\([^.]*\)\">\([^.]*\)</foreign> </title>|\x5cqa \5 \n\              </verse><verse osisID=\"\1.\2.\3\"> \x5cp |g" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
echo " "
# cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep -1 "qa"
# ==============================




# ================= Naslovi Psalmov ====================
echo -E " "
echo -E "   --==     Naslovi v Psalmih  Ulovi med  >  Naslov in potem v naslednji vrstici presledki in potem  \</title>\<verse    "
echo -E "   --==     \d                      <title type=\"psalm\" canonical=\"true\">    </title>                                "
sed -i "s|              <title type=\"psalm\" canonical=\"true\">|<mt2>\x5cd|g"          /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|\\.</title>|.</mt2>|g"          /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Zgoraj sem dodaml Y   Sedaj ga tukaj jemljem proc.

  #   OLD  sed -i "s|Y</title>\n|XXYYmt2XX|g"          /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#  Y title in prvo vrstico potegne gor in da vse v eno vrstico
sed  -z -i 's|Y</title>\n                      <verse osisID="Ps.[0-9]*.1">|XXYYmt2XX|g' /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

# mt2 moram spremeniti v prvo vrstico    Ja vedno je Ps.1   narobe toda za paratex bo dobro
sed  -i 's|<mt2>|                      <verse osisID=\"Ps.1.1\">|g' /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml




# Izjema v Ps 52.0 54 ker ni pike na koncu vrstice.
# cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep 'pred svojim sinom'
# =======================================================

echo -E "   --==     Psalm 22 6  Skrlatni crv..."
# zamenja <lb />   z nic
sed -i "s|<lb />||g"                                                                         /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Zamenja <hi type="bold"> </hi>     z   \bd   \bd*
sed -i "s|<hi type=\"bold\">| \\\bd |g"                                                         /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|</hi>| \\\bd* |g"                                                                    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

# cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep 'Ps.22.6"'


echo -E "   --== Odstrani rdece JEZUSOVE BESEDE ==--"
#Odstranil \wj... ker mi potem ni delovale vgnezdenje referenc
# problem so italic in dodane  reference
# Vgnezdenim zadevam moras dati spredaj bacslash in plus  
#echo -E " "
#echo -E "   --==   	Words of Jesus begin  <q who=\"Jesus\" marker=\"\">  \</q>    "
#echo -E "   --==   \wj     \wj*    "
# sed -i "s|<q who=\"Jesus\" marker=\"\">|\x5cwj |g"            /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed  -i "s|<q who=\"Jesus\" marker=\"\">||g"            /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# sed -i "s|</q>|\x5cwj* |g"                                    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|</q>||g"                                    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "<q who="
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "<q>"
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "wj"
# ========================================================


# Odstranil +   pri \+w
# ==================== SVETO <INSCRIPTION> ===================
echo -E " "
echo -E "   --==   	<inscription>SVETO  \nd Gospodu \nd* </inscription>    "
echo -E "   --==        \+w      \nd Gospodu \nd*    \+w*   "
sed -i "s|<inscription>|\x5cw |g"                             /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|</inscription>|\x5cw*|g"                             /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "Exod.28.36"
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "<inscription>"
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "</inscription>"
# ============================================================


# ===================== SELAH ================================
echo -E " "
echo -E "   --==     </verse><lg><l type=\"selah\"> Sela.</l></lg>    "
echo -E "   --==       \qs  \qs*    "
sed -i "s|\(</verse>\)<lg><l type=\"selah\">\([^.]*\).</l></lg>| \x5cqs\2\x5cqs*\n              \1|g"           /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Sedaj pa potegnem gor tretjo vrstico, ker je </verse> padel v drugo vrstico in zdruzim s tretjo vrstico
#              </verse>
#                      <verse osisID=
sed -i 'N;s|              </verse>\n                      <verse osisID=|              </verse><verse osisID=|'  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "selah"
# cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "\qs"
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep -F 'type="selah">'
#=============================================================



# ===================== DIV TYPE BOOK ================================
#      Popraviti zaradi python skripta
#           <div type=\"book\" osisID=\"Gen\">  ->   <div type=\"book\">
echo -E " "
sed -i "s|<div type=\"book\" osisID=\"\([^.]*\)\">     |<div type=\"book\">|g"           /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "book\"osisID="
#=============================================================


# ===================== DIV TYPE BOOKGROUP ================================
#      Popraviti zaradi python skripta
#    <div type=\"bookGroup\" subType=\"x-OT\" canonical=\"true\">   ->    <div type=\"x-testament\">
#    <div type=\"bookGroup\" subType=\"x-NT\" canonical=\"true\">   ->    <div type=\"x-testament\">
echo -E " "
sed -i "s|<div type=\"bookGroup\" subType=\"x-OT\" canonical=\"true\">|<div type=\"x-testament\">|g"           /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|<div type=\"bookGroup\" subType=\"x-NT\" canonical=\"true\">|<div type=\"x-testament\">|g"           /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "bookGroup"
#=============================================================


# ===================== VERSE OSIS ID ODSTRANI ================================
#      Popraviti zaradi python skripta
#    <verse osisID=\"Gen.1.2\">   ->   <verse>
echo -E " "
sed -i "s|<verse osisID=\"\([^.]*\).\([^.]*\).\([^.]*\)\">|<verse>|g"       /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep -F '<verse osisID=\"Gen.1.2\">'
# Sedaj ostanejo vrstice:
#        </verse></chapter><chapter osisID="Rev.22" chapterTitle="22. Poglavje"><title type="chapter">22. Poglavje</title>
#=============================================================




# ===================== CHAPTER OSIS ID ODSTRANI ================================
#      Popraviti zaradi python skripta
#    <chapter osisID=\"Gen.01\" chapterTitle=\"1. Poglavje\">   ->   <chapter>
echo -E " "
sed -i  "s|<chapter osisID=\"\([^.]*\).\([^.]*\)\" chapterTitle=\"\([^.]*\). Poglavje\"><title type=\"chapter\">\([^.]*\). Poglavje</title>|<chapter>\4. Poglavje|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#sed -i "s|<chapter osisID=\"\([^.]*\).\([^.]*\)\" chapterTitle=\"\([^.]*\). Poglavje\"><verse|<chapter>\x5cp \x5cn _C_\4. Poglavje|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep -F '<chapter osisID="Gen.01" chapterTitle="1. Poglavje\">'
# cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep -F '<chapter'   # xx

echo -E " "
#   Se pri Psalmih
#    <chapter osisID=\"Ps.100\" chapterTitle=\"Psalm 100\"><title type=\"chapter\">Psalm 100</title>      ->   <chapter> Psalm 100
#         <chapter osisID=\"Ps.100\" chapterTitle=\"Psalm 100\"><title type=\"chapter\">Psalm 100</title>
sed -i "s|<chapter osisID=\"\([^.]*\).\([^.]*\)\" chapterTitle=\"\([^.]*\)\"><title type=\"chapter\">\([^.]*\)</title>|<chapter>\x5cp \x5cn _P_\4|g"   /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep -F 'chapter osisID="Ps.100" chapterTitle="Psalm 100">'
# cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep -F '<chapter>\p '
#=============================================================



# ===================== CHAPTER OSIS ID ODSTRANI ================================
#      Popraviti zaradi python skripta
echo -E " "
#<?xml version=\"1.0\" encoding=\"UTF-8\" ?>
#<osis xmlns=\"http://www.bibletechnologies.net/2003/OSIS/namespace\"
#       xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
#       xsi:schemaLocation=\"http://www.bibletechnologies.net/2003/OSIS/namespace http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd\">
#            ->    <osis>
#
sed -i "s|<?xml version=\"1.0\" encoding=\"UTF-8\" ?>||g"                                      /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|<osis xmlns=\"http://www.bibletechnologies.net/2003/OSIS/namespace\"|<osis>|g"       /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|      xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"||g"                    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
sed -i "s|      xsi:schemaLocation=\"http://www.bibletechnologies.net/2003/OSIS/namespace http://www.crosswire.org/~dmsmith/osis/osisCore.2.1.1-cw-latest.xsd\">||g"    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#
#<osisText osisIDWork=\"SloKJV\" osisRefWork=\"Bible\" xml:lang=\"sl\">
#            ->    <osisText>
sed -i "s|<osisText osisIDWork=\"SloKJV\" osisRefWork=\"Bible\" xml:lang=\"sl\">|<osisText>|g"    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml

cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep "xmlns"
#=============================================================


# ===================== POBRISE VSE TITLE ================================
#      Popraviti zaradi python skripta  ???????
#        <title>Sveto pismo Kralja Jakoba (1769) – SloKJV</title>
sed -i "s|<title>\([^.]*\)</title>|\1|g"                                      /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# cat SloKJV_sword.xml |grep  "Sveto pismo Kralja Jakoba"
cat SloKJV_sword.xml |grep  "SloKJV</title>"
#     <title type=\"main\">Stara zaveza</title>
sed -i "s|<title type=\"main\">\([^.]*\)</title>|\1|g"                                      /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#cat SloKJV_sword.xml |grep  "Nova zaveza"
	#cat SloKJV_sword.xml |grep  "Stara zaveza</title>"
#          <title type=\"main\" short=\"Geneza\">Prva Mojzesova knjiga, imenovana Geneza</title>
#          <title type=\"main\" short=\"Matej\">Evangelij po Sv. Mateju</title>
# To je za tiste naslove knjig ki nimajo notri nobene pike
sed -i 's|<title type=\"main\" short=\"\([^.]*\)\">\([^.]*\)</title>|\1_X_\2|g'    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# To je za tiste naslove knjig ki nimajo notri eno piko
sed -i 's|<title type=\"main\" short=\"\([^.]*\)\">\([^.]*\).\([^.]*\)</title>|\1_Y_\2.\3|g'        /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# cat SloKJV_sword.xml |grep -F '<title type="main"'
#cat SloKJV_sword.xml |grep -F '<div type="book">'
#cat SloKJV_sword.xml |grep  "_X_"
#cat SloKJV_sword.xml |grep  "_Y_"
#=========================================================================



#=================== ODSTRANI PRESLEDKE ==================================
# Odstrani presledke, enega ali vec, na zacetku vrstic
sed -i "s/^[ ]*//g"                                      /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Odstrani presledke, enega ali vec, na zacetku vrstic
sed -i "s/^<verse>[ ]*/<verse>/g"                        /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Odstrani presledke, enega ali vec, na koncu vrstic
sed -i 's/ *$//'                                         /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Odstrani presledek med  <verse> TEXT     na zacetku vrstic
sed -i 's/^<verse> /<verse>/'                            /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Odstrani presledek, enega ali vec, med  <verse></verse> TEXT     na zacetku vrstic
#  Bibleedit na 127.0.0.1:8080 se pritozuje in je treba odstraniti
sed -i "s|</verse><verse> |</verse><verse>|g"            /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Potegne gor 38 vrstic v Psalmih
sed -i ':a;N;$!ba;s|</verse>\n<verse>|</verse><verse>|g' /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep  -2 "Zlobni bodo na"
#=========================================================================


# ================== Odstrani prazne vrstice ================================
sed -i -e "/^$/d" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# V prvi vrstici poglavja naredi odstavek, tam, kjer ker se pricne z opombo.
#       <verse>  \f     ->    <verse>  \p \f
sed -i "s|<verse> \\\f |<verse> \x5cp \x5cf |g"    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# ============================================================================


# ===================== KOLOFON ================================
#Pripravi kolofon za       \cls
#         ]
#</div>
sed -i ':a;N;$!ba;s|]\n</div>|]</verse></chapter>|g'       /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#</verse></chapter>
#<div type=\"colophon\" osisID=\"Titus.c\">
sed -i ':a;N;$!ba;s|</verse></chapter>\n<div type=\"colophon\" osisID=\"\([^.]*\).c\">|\x5ccls|g'       /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep -2 "Titus.c"
#=============================================================


# ===================== INTRODUCTION UVOD========================
# TO zamenja s \ip   Introduction paragraph
# div type="introduction">         <p type="x-noindent" subType="x-introduction">
#sed -i "s|<div type=\"introduction\">         <p type=\"x-noindent\" subType=\"x-introduction\">|<introduction>|g"  /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
# Potegne gor vrstico  </p> ENTER </div>
sed -i ':a;N;$!ba;s|<\/p>\n<\/div>|</p></div>|g'                                                   /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#Zamenja  </p></div>  z nic
#sed -i "s|<\/p><\/div>|<\/introduction>|g" /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
echo  Odstrani vrstice z Uvodom da je stevilcenje poglavij v redu dokler se ne naredi boljsi osis2usfm.py
sed -i '/<div type=\"introduction\">/d'                                /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep introduction
# exit
#================================================================



# ===================== PSALMI ================================

# cat /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml |grep -10 "Psalm 4"

#=============================================================



#=============================================================
#  Doda se eno kvazi prazno knjigo da je     Mt  41-ta knjiga namesto 40
#                                        in  Raz 67-ta knjiga namesto 66 
#       </verse></chapter></div></div>      spremeni v    </verse></chapter></div><div type="book"></div></div>   
sed -i "s|<\/verse><\/chapter><\/div><\/div>|<\/verse><\/chapter><\/div><div type=\"book\"><\/div><\/div>|g"    /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#=============================================================



#=========================================================================
echo -E "   --== Pozene generiranje usfm datotek==--   "
# Pobrise vse prejsnje usfm datoteke
rm /home/pc/Dokumenti/osis2usfm/*.usfm  >/dev/null 2>&1
rm $SloKJV$format/*.usfm >/dev/null 2>&1
# Pobrise vse prejsnje PDF datoteke   in ne izpise napake na ekranu
rm $SloKJV$format/local/ptxprint/*.pdf >/dev/null 2>&1
echo -E "python3 osis2usfm.py SloKJV_sword.xml"
python3 osis2usfm.py SloKJV_sword.xml




# Pobrise 40-to kvazi knjigo da so knjige Nove zaveze pravilno ostevilcene
rm     /home/pc/Dokumenti/osis2usfm/40____.usfm
#=========================================================================


# XXX sed -i "s/^\\\\v \([0-9]*\) \\\\p /\x5cp\n\x5cv \1 /g"  $SloKJV$format/64_2JN.usfm | cat $SloKJV$format/64_2JN.usfm

echo -E "   --==  Prestavi usfm datotke v pravo mapo za PTXPRINT"
mv /home/pc/Dokumenti/osis2usfm/*.usfm $SloKJV$format/ >/dev/null 2>&1
echo -E "======= Koncal generiranje usfm datotek === "

echo -E "   --==      Popravi  znak \p eno vrstico visje v vseh usfm datotekah"
#                    > \p   
#    \v 6 \p Text    > \v 6 Text
sed -i "s/^\\\\v \([0-9]*\) \\\\p /\x5cp\n\x5cv \1 /g"  $SloKJV$format/*.usfm 

# Izklopil, ker je delalo tezave in se uporablja pri Psalmih
# Popravi  znak \c eno vrstico visje doda \b kar pomeni prazno vrstico pred poglavjem
#                > \b   
#    \c 6 Text   > \c 6 Text
#sed -i "s/^\\\\c \([0-9]*\)/\x5cb\n\x5cc \1 /g"         $SloKJV$format/*.usfm
# cat $SloKJV$format/67_REV.usfm


echo -E "   --==  Takoj za zacetkom poglavja naredi odstavek ==--"
#   \c stevilka    ->   \c stevilka
#                       \p
sed -i "s/^\\\\c \([0-9]*\)/\x5cc \1\n\x5cp/g"         $SloKJV$format/*.usfm


echo -E "   --==  Kjer sta opomba in referenca skupaj naredi presledek ==--"
#      \add*\x   ->    \add* \x
sed -i "s/\\\\add\*\\\\x/\x5cadd\* \x5cx/g"             $SloKJV$format/*.usfm
#========================================================


#echo -E "======================================="
#tail /home/pc/Dokumenti/osis2usfm/run_osis2usfm
#echo -E "======================================="
#head /home/pc/Dokumenti/osis2usfm/SloKJV_sword.xml
#echo -E "======================================="
#head -20 $SloKJV$format/66_JUD.usfm
#echo -E "======================================="

# Naredi eno samo USFM datoteko, ki jo potem 15 minut uvaza v Bibledit
#rm  $SloKJV$format/1*.usfm  >/dev/null 2>&1
#cat $SloKJV$format/*.usfm  >  $SloKJV$format/1_VSI.usfm
#cat $SloKJV$format/1*.usfm >> $SloKJV$format/1_SZ_VSI.usfm
#cat $SloKJV$format/2*.usfm >> $SloKJV$format/1_SZ_VSI.usfm
#cat $SloKJV$format/3*.usfm >> $SloKJV$format/1_SZ_VSI.usfm
#cat $SloKJV$format/4*.usfm >> $SloKJV$format/1_NZ_VSI.usfm
#cat $SloKJV$format/5*.usfm >> $SloKJV$format/1_NZ_VSI.usfm
#cat $SloKJV$format/6*.usfm >> $SloKJV$format/1_NZ_VSI.usfm

echo -E "   --==  Pozene izdelavo PDF datoteke ==--"
echo -E "   --==  Popravi naslove knjig ==--"

# \h 1 Pet
# \h1 Prvo Petrovo pismo
# \toc1 Prvo Petrovo pismo
# \toc2 1 Peter
# \toc3 1 Pet
# \mt1 Prvo Petrovo pismo


# GEN
  sed -i "s/\\\\h  /\x5ch 1 Mz/g"                                                                $SloKJV$format/01_GEN.usfm
  sed -i "s/\\\\h1/\x5ch1 Prva Mojzesova knjiga, imenovana Geneza/g"                             $SloKJV$format/01_GEN.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Prva Mojzesova knjiga, imenovana Geneza/g"                         $SloKJV$format/01_GEN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Geneza/g"                                                          $SloKJV$format/01_GEN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Mz/g"                                                             $SloKJV$format/01_GEN.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Prva Mojzesova knjiga, imenovana Geneza/g"                           $SloKJV$format/01_GEN.usfm

# EXO
  sed -i "s/\\\\h  /\x5ch 2 Mz/g"                                                                $SloKJV$format/02_EXO.usfm
  sed -i "s/\\\\h1/\x5ch1 Druga Mojzesova knjiga, imenovana Eksodus/g"                           $SloKJV$format/02_EXO.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Druga Mojzesova knjiga, imenovana Eksodus/g"                       $SloKJV$format/02_EXO.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Eksodus/g"                                                         $SloKJV$format/02_EXO.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Mz/g"                                                             $SloKJV$format/02_EXO.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Druga Mojzesova knjiga, imenovana Eksodus/g"                         $SloKJV$format/02_EXO.usfm

# LEV
  sed -i "s/\\\\h  /\x5ch 3 Mz/g"                                                                $SloKJV$format/03_LEV.usfm
  sed -i "s/\\\\h1/\x5ch1 Tretja Mojzesova knjiga, imenovana Levitik/g"                          $SloKJV$format/03_LEV.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Tretja Mojzesova knjiga, imenovana Levitik/g"                      $SloKJV$format/03_LEV.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Levitik/g"                                                         $SloKJV$format/03_LEV.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 3Mz/g"                                                             $SloKJV$format/03_LEV.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Tretja Mojzesova knjiga, imenovana Levitik/g"                        $SloKJV$format/03_LEV.usfm
 
# NUM
  sed -i "s/\\\\h  /\x5ch 4 Mz/g"                                                                $SloKJV$format/04_NUM.usfm
  sed -i "s/\\\\h1/\x5ch1 Četrta Mojzesova knjiga, imenovana Numeri/g"                           $SloKJV$format/04_NUM.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Četrta Mojzesova knjiga, imenovana Numeri/g"                       $SloKJV$format/04_NUM.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Numeri/g"                                                          $SloKJV$format/04_NUM.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 4Mz/g"                                                             $SloKJV$format/04_NUM.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Četrta Mojzesova knjiga, imenovana Numeri/g"                         $SloKJV$format/04_NUM.usfm

# DEU
  sed -i "s/\\\\h  /\x5ch 5 Mz/g"                                                                $SloKJV$format/05_DEU.usfm
  sed -i "s/\\\\h1/\x5ch1 Peta Mojzesova knjiga, imenovana Devteronomij/g"                       $SloKJV$format/05_DEU.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Peta Mojzesova knjiga, imenovana Devteronomij/g"                   $SloKJV$format/05_DEU.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Devteronomij/g"                                                    $SloKJV$format/05_DEU.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 5Mz/g"                                                             $SloKJV$format/05_DEU.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Peta Mojzesova knjiga, imenovana Devteronomij/g"                     $SloKJV$format/05_DEU.usfm

# JOS
  sed -i "s/\\\\h  /\x5ch Joz/g"                                                                 $SloKJV$format/06_JOS.usfm
  sed -i "s/\\\\h1/\x5ch1 Jozuetova knjiga/g"                                                    $SloKJV$format/06_JOS.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Jozuetova knjiga/g"                                                $SloKJV$format/06_JOS.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Jozue/g"                                                           $SloKJV$format/06_JOS.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Joz/g"                                                             $SloKJV$format/06_JOS.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Jozuetova knjiga/g"                                                  $SloKJV$format/06_JOS.usfm

# JDG
  sed -i "s/\\\\h  /\x5ch Sod/g"                                                                 $SloKJV$format/07_JDG.usfm
  sed -i "s/\\\\h1/\x5ch1 Knjiga sodnikov/g"                                                     $SloKJV$format/07_JDG.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Knjiga sodnikov/g"                                                 $SloKJV$format/07_JDG.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Sodniki/g"                                                         $SloKJV$format/07_JDG.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Sod/g"                                                             $SloKJV$format/07_JDG.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Knjiga sodnikov/g"                                                   $SloKJV$format/07_JDG.usfm

# RUT
  sed -i "s/\\\\h  /\x5ch Ruta/g"                                                                $SloKJV$format/08_RUT.usfm
  sed -i "s/\\\\h1/\x5ch1 Rutina knjiga/g"                                                       $SloKJV$format/08_RUT.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Rutina knjiga/g"                                                   $SloKJV$format/08_RUT.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Ruta/g"                                                            $SloKJV$format/08_RUT.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Rut/g"                                                             $SloKJV$format/08_RUT.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Rutina knjiga/g"                                                     $SloKJV$format/08_RUT.usfm

# 1SA
  sed -i "s/\\\\h  /\x5ch 1 Sam/g"                                                               $SloKJV$format/09_1SA.usfm
  sed -i "s/\\\\h1/\x5ch1 Prva Samuelova knjiga, drugače imenovana Prva knjiga kraljev/g"        $SloKJV$format/09_1SA.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Prva Samuelova knjiga, drugače imenovana Prva knjiga kraljev/g"    $SloKJV$format/09_1SA.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Samuel/g"                                                        $SloKJV$format/09_1SA.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Sa/g"                                                             $SloKJV$format/09_1SA.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Prva Samuelova knjiga, drugače imenovana Prva knjiga kraljev/g"      $SloKJV$format/09_1SA.usfm

# 2SA
  sed -i "s/\\\\h  /\x5ch 2 Sam/g"                                                               $SloKJV$format/10_2SA.usfm
  sed -i "s/\\\\h1/\x5ch1 Druga Samuelova knjiga, drugače imenovana Druga knjiga kraljev/g"      $SloKJV$format/10_2SA.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Druga Samuelova knjiga, drugače imenovana Druga knjiga kraljev/g"  $SloKJV$format/10_2SA.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Samuel/g"                                                        $SloKJV$format/10_2SA.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Sa/g"                                                             $SloKJV$format/10_2SA.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Druga Samuelova knjiga, drugače imenovana Druga knjiga kraljev/g"    $SloKJV$format/10_2SA.usfm

# 1KI
  sed -i "s/\\\\h  /\x5ch 1 Kr/g"                                                                $SloKJV$format/11_1KI.usfm
  sed -i "s/\\\\h1/\x5ch1 Prva knjiga kraljev, pogosto imenovana Tretja knjiga kraljev/g"        $SloKJV$format/11_1KI.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Prva knjiga kraljev, pogosto imenovana Tretja knjiga kraljev/g"    $SloKJV$format/11_1KI.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Kralji/g"                                                        $SloKJV$format/11_1KI.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Kr/g"                                                             $SloKJV$format/11_1KI.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Prva knjiga kraljev, pogosto imenovana Tretja knjiga kraljev/g"      $SloKJV$format/11_1KI.usfm

# 2KI
  sed -i "s/\\\\h  /\x5ch 2 Kr/g"                                                                $SloKJV$format/12_2KI.usfm
  sed -i "s/\\\\h1/\x5ch1 Druga knjiga kraljev, pogosto imenovana Četrta knjiga kraljev/g"       $SloKJV$format/12_2KI.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Druga knjiga kraljev, pogosto imenovana Četrta knjiga kraljev/g"   $SloKJV$format/12_2KI.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Kralji/g"                                                        $SloKJV$format/12_2KI.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Kr/g"                                                             $SloKJV$format/12_2KI.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Druga knjiga kraljev, pogosto imenovana Četrta knjiga kraljev/g"     $SloKJV$format/12_2KI.usfm

# 1CH
  sed -i "s/\\\\h  /\x5ch 1 Krn/g"                                                               $SloKJV$format/13_1CH.usfm
  sed -i "s/\\\\h1/\x5ch1 Prva kroniška knjiga/g"                                                $SloKJV$format/13_1CH.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Prva kroniška knjiga/g"                                            $SloKJV$format/13_1CH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Kroniška/g"                                                      $SloKJV$format/13_1CH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Krn/g"                                                            $SloKJV$format/13_1CH.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Prva kroniška knjiga/g"                                              $SloKJV$format/13_1CH.usfm

# 2CH
  sed -i "s/\\\\h  /\x5ch 2 Krn/g"                                                               $SloKJV$format/14_2CH.usfm
  sed -i "s/\\\\h1/\x5ch1 Druga kroniška knjiga/g"                                               $SloKJV$format/14_2CH.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Druga kroniška knjiga/g"                                           $SloKJV$format/14_2CH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Kroniška/g"                                                      $SloKJV$format/14_2CH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Krn/g"                                                            $SloKJV$format/14_2CH.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Druga kroniška knjiga/g"                                             $SloKJV$format/14_2CH.usfm

# EZR
  sed -i "s/\\\\h  /\x5ch Ezra/g"                                                                $SloKJV$format/15_EZR.usfm
  sed -i "s/\\\\h1/\x5ch1 Ezrova knjiga/g"                                                       $SloKJV$format/15_EZR.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Ezrova knjiga/g"                                                   $SloKJV$format/15_EZR.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Ezra/g"                                                            $SloKJV$format/15_EZR.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Ezr/g"                                                             $SloKJV$format/15_EZR.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Ezrova knjiga/g"                                                     $SloKJV$format/15_EZR.usfm

# NEH
  sed -i "s/\\\\h  /\x5ch Neh/g"                                                                 $SloKJV$format/16_NEH.usfm
  sed -i "s/\\\\h1/\x5ch1 Nehemijeva knjiga/g"                                                   $SloKJV$format/16_NEH.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Nehemijeva knjiga/g"                                               $SloKJV$format/16_NEH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Nehemija/g"                                                        $SloKJV$format/16_NEH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Neh/g"                                                             $SloKJV$format/16_NEH.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Nehemijeva knjiga/g"                                                 $SloKJV$format/16_NEH.usfm

# EST
  sed -i "s/\\\\h  /\x5ch Est/g"                                                                 $SloKJV$format/17_EST.usfm
  sed -i "s/\\\\h1/\x5ch1 Esterina knjiga/g"                                                     $SloKJV$format/17_EST.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Esterina knjiga/g"                                                 $SloKJV$format/17_EST.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Estera/g"                                                          $SloKJV$format/17_EST.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Est/g"                                                             $SloKJV$format/17_EST.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Esterina knjiga/g"                                                   $SloKJV$format/17_EST.usfm

# JOB
  sed -i "s/\\\\h  /\x5ch Job/g"                                                                 $SloKJV$format/18_JOB.usfm
  sed -i "s/\\\\h1/\x5ch1 Jobova knjiga/g"                                                       $SloKJV$format/18_JOB.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Jobova knjiga/g"                                                   $SloKJV$format/18_JOB.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Job/g"                                                             $SloKJV$format/18_JOB.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Job/g"                                                             $SloKJV$format/18_JOB.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Jobova knjiga/g"                                                     $SloKJV$format/18_JOB.usfm

# PSA
  sed -i "s/\\\\h  /\x5ch Ps/g"                                                                  $SloKJV$format/19_PSA.usfm
  sed -i "s/\\\\h1/\x5ch1 Knjiga Psalmov/g"                                                      $SloKJV$format/19_PSA.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Knjiga Psalmov/g"                                                  $SloKJV$format/19_PSA.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Psalmi/g"                                                          $SloKJV$format/19_PSA.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Ps/g"                                                              $SloKJV$format/19_PSA.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Knjiga Psalmov/g"                                                    $SloKJV$format/19_PSA.usfm

# PRO
  sed -i "s/\\\\h  /\x5ch Prg/g"                                                                 $SloKJV$format/20_PRO.usfm
  sed -i "s/\\\\h1/\x5ch1 Pregovori/g"                                                           $SloKJV$format/20_PRO.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Pregovori/g"                                                       $SloKJV$format/20_PRO.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Pregovori/g"                                                       $SloKJV$format/20_PRO.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Prg/g"                                                             $SloKJV$format/20_PRO.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Pregovori/g"                                                         $SloKJV$format/20_PRO.usfm

# ECC
  sed -i "s/\\\\h  /\x5ch Prd/g"                                                                 $SloKJV$format/21_ECC.usfm
  sed -i "s/\\\\h1/\x5ch1 Kohelet ali Pridigar/g"                                                $SloKJV$format/21_ECC.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Kohelet ali Pridigar/g"                                            $SloKJV$format/21_ECC.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Pridigar/g"                                                        $SloKJV$format/21_ECC.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Prd/g"                                                             $SloKJV$format/21_ECC.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Kohelet ali Pridigar/g"                                              $SloKJV$format/21_ECC.usfm

# SNG
  sed -i "s/\\\\h  /\x5ch Pp/g"                                                                  $SloKJV$format/22_SNG.usfm
  sed -i "s/\\\\h1/\x5ch1 Salomonova pesem (hebr. Pesem pesmi)/g"                                $SloKJV$format/22_SNG.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Salomonova pesem (hebr. Pesem pesmi)/g"                            $SloKJV$format/22_SNG.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Pesem pesmi/g"                                                     $SloKJV$format/22_SNG.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Pp/g"                                                              $SloKJV$format/22_SNG.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Salomonova pesem (hebr. Pesem pesmi)/g"                              $SloKJV$format/22_SNG.usfm

# ISA
  sed -i "s/\\\\h  /\x5ch Iz/g"                                                                  $SloKJV$format/23_ISA.usfm
  sed -i "s/\\\\h1/\x5ch1 Knjiga preroka Izaija/g"                                               $SloKJV$format/23_ISA.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Knjiga preroka Izaija/g"                                           $SloKJV$format/23_ISA.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Izaija/g"                                                          $SloKJV$format/23_ISA.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Iz/g"                                                              $SloKJV$format/23_ISA.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Knjiga preroka Izaija/g"                                             $SloKJV$format/23_ISA.usfm

# JER
  sed -i "s/\\\\h  /\x5ch Jer/g"                                                                 $SloKJV$format/24_JER.usfm
  sed -i "s/\\\\h1/\x5ch1 Knjiga preroka Jeremija/g"                                             $SloKJV$format/24_JER.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Knjiga preroka Jeremija/g"                                         $SloKJV$format/24_JER.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Jeremija/g"                                                        $SloKJV$format/24_JER.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jer/g"                                                             $SloKJV$format/24_JER.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Knjiga preroka Jeremija/g"                                           $SloKJV$format/24_JER.usfm

# LAM
  sed -i "s/\\\\h  /\x5ch Žal/g"                                                                 $SloKJV$format/25_LAM.usfm
  sed -i "s/\\\\h1/\x5ch1 Jeremijeve žalostinke/g"                                               $SloKJV$format/25_LAM.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Jeremijeve žalostinke/g"                                           $SloKJV$format/25_LAM.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Žalostinke/g"                                                      $SloKJV$format/25_LAM.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Žal/g"                                                             $SloKJV$format/25_LAM.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Jeremijeve žalostinke/g"                                             $SloKJV$format/25_LAM.usfm

# EZK
  sed -i "s/\\\\h  /\x5ch Ezk/g"                                                                 $SloKJV$format/26_EZK.usfm
  sed -i "s/\\\\h1/\x5ch1 Knjiga preroka Ezekiela/g"                                             $SloKJV$format/26_EZK.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Knjiga preroka Ezekiela/g"                                         $SloKJV$format/26_EZK.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Ezekiel/g"                                                         $SloKJV$format/26_EZK.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Ezk/g"                                                             $SloKJV$format/26_EZK.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Knjiga preroka Ezekiela/g"                                           $SloKJV$format/26_EZK.usfm

# DAN
  sed -i "s/\\\\h  /\x5ch Dan/g"                                                                 $SloKJV$format/27_DAN.usfm
  sed -i "s/\\\\h1/\x5ch1 Danielova knjiga/g"                                                    $SloKJV$format/27_DAN.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Danielova knjiga/g"                                                $SloKJV$format/27_DAN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Daniel/g"                                                          $SloKJV$format/27_DAN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Dan/g"                                                             $SloKJV$format/27_DAN.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Danielova knjiga/g"                                                  $SloKJV$format/27_DAN.usfm

# HOS
  sed -i "s/\\\\h  /\x5ch Oz/g"                                                                  $SloKJV$format/28_HOS.usfm
  sed -i "s/\\\\h1/\x5ch1 Ozej/g"                                                                $SloKJV$format/28_HOS.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Ozej/g"                                                            $SloKJV$format/28_HOS.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Ozej/g"                                                            $SloKJV$format/28_HOS.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Oz/g"                                                              $SloKJV$format/28_HOS.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Ozej/g"                                                              $SloKJV$format/28_HOS.usfm

# JOL
  sed -i "s/\\\\h  /\x5ch Jl/g"                                                                  $SloKJV$format/29_JOL.usfm
  sed -i "s/\\\\h1/\x5ch1 Joel/g"                                                                $SloKJV$format/29_JOL.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Joel/g"                                                            $SloKJV$format/29_JOL.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Joel/g"                                                            $SloKJV$format/29_JOL.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jl/g"                                                              $SloKJV$format/29_JOL.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Joel/g"                                                              $SloKJV$format/29_JOL.usfm

# AMO
  sed -i "s/\\\\h  /\x5ch Am/g"                                                                  $SloKJV$format/30_AMO.usfm
  sed -i "s/\\\\h1/\x5ch1 Amos/g"                                                                $SloKJV$format/30_AMO.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Amos/g"                                                            $SloKJV$format/30_AMO.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Amos/g"                                                            $SloKJV$format/30_AMO.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Am/g"                                                              $SloKJV$format/30_AMO.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Amos/g"                                                              $SloKJV$format/30_AMO.usfm

# OBA
  sed -i "s/\\\\h  /\x5ch Abd/g"                                                                 $SloKJV$format/31_OBA.usfm
  sed -i "s/\\\\h1/\x5ch1 Abdija/g"                                                              $SloKJV$format/31_OBA.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Abdija/g"                                                          $SloKJV$format/31_OBA.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Abdija/g"                                                          $SloKJV$format/31_OBA.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Abd/g"                                                             $SloKJV$format/31_OBA.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Abdija/g"                                                            $SloKJV$format/31_OBA.usfm

# JON
  sed -i "s/\\\\h  /\x5ch Jon/g"                                                                 $SloKJV$format/32_JON.usfm
  sed -i "s/\\\\h1/\x5ch1 Jona/g"                                                                $SloKJV$format/32_JON.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Jona/g"                                                            $SloKJV$format/32_JON.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Jona/g"                                                            $SloKJV$format/32_JON.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jon/g"                                                             $SloKJV$format/32_JON.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Jona/g"                                                              $SloKJV$format/32_JON.usfm

# MIC
  sed -i "s/\\\\h  /\x5ch Mih/g"                                                                 $SloKJV$format/33_MIC.usfm
  sed -i "s/\\\\h1/\x5ch1 Mihej/g"                                                               $SloKJV$format/33_MIC.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Mihej/g"                                                           $SloKJV$format/33_MIC.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Mihej/g"                                                           $SloKJV$format/33_MIC.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Mih/g"                                                             $SloKJV$format/33_MIC.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Mihej/g"                                                             $SloKJV$format/33_MIC.usfm

# NAM
  sed -i "s/\\\\h  /\x5ch Nah/g"                                                                 $SloKJV$format/34_NAM.usfm
  sed -i "s/\\\\h1/\x5ch1 Nahum/g"                                                               $SloKJV$format/34_NAM.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Nahum/g"                                                           $SloKJV$format/34_NAM.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Nahum/g"                                                           $SloKJV$format/34_NAM.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Nah/g"                                                             $SloKJV$format/34_NAM.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Nahum/g"                                                             $SloKJV$format/34_NAM.usfm

# HAB
  sed -i "s/\\\\h  /\x5ch Hab/g"                                                                 $SloKJV$format/35_HAB.usfm
  sed -i "s/\\\\h1/\x5ch1 Habakuk/g"                                                             $SloKJV$format/35_HAB.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Habakuk/g"                                                         $SloKJV$format/35_HAB.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Habakuk/g"                                                         $SloKJV$format/35_HAB.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Hab/g"                                                             $SloKJV$format/35_HAB.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Habakuk/g"                                                           $SloKJV$format/35_HAB.usfm

# ZEP
  sed -i "s/\\\\h  /\x5ch Sof/g"                                                                 $SloKJV$format/36_ZEP.usfm
  sed -i "s/\\\\h1/\x5ch1 Sofonija/g"                                                            $SloKJV$format/36_ZEP.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Sofonija/g"                                                        $SloKJV$format/36_ZEP.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Sofonija/g"                                                        $SloKJV$format/36_ZEP.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Sof/g"                                                             $SloKJV$format/36_ZEP.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Sofonija/g"                                                          $SloKJV$format/36_ZEP.usfm

# HAG
  sed -i "s/\\\\h  /\x5ch Ag/g"                                                                  $SloKJV$format/37_HAG.usfm
  sed -i "s/\\\\h1/\x5ch1 Agej/g"                                                                $SloKJV$format/37_HAG.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Agej/g"                                                            $SloKJV$format/37_HAG.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Agej/g"                                                            $SloKJV$format/37_HAG.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Ag/g"                                                              $SloKJV$format/37_HAG.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Agej/g"                                                              $SloKJV$format/37_HAG.usfm

# ZEC
  sed -i "s/\\\\h  /\x5ch Zah/g"                                                                 $SloKJV$format/38_ZEC.usfm
  sed -i "s/\\\\h1/\x5ch1 Zaharija/g"                                                            $SloKJV$format/38_ZEC.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Zaharija/g"                                                        $SloKJV$format/38_ZEC.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Zaharija/g"                                                        $SloKJV$format/38_ZEC.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Zah/g"                                                             $SloKJV$format/38_ZEC.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Zaharija/g"                                                          $SloKJV$format/38_ZEC.usfm

# MAL
  sed -i "s/\\\\h  /\x5ch Mal/g"                                                                 $SloKJV$format/39_MAL.usfm
  sed -i "s/\\\\h1/\x5ch1 Malahija/g"                                                            $SloKJV$format/39_MAL.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Malahija/g"                                                        $SloKJV$format/39_MAL.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Malahija/g"                                                        $SloKJV$format/39_MAL.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Mal/g"                                                             $SloKJV$format/39_MAL.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Malahija/g"                                                          $SloKJV$format/39_MAL.usfm

# MAT
  sed -i "s/\\\\h  /\x5ch Mt/g"                                                                  $SloKJV$format/41_MAT.usfm
  sed -i "s/\\\\h1/\x5ch1 Evangelij po Sv. Mateju/g"                                             $SloKJV$format/41_MAT.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Evangelij po Sv. Mateju/g"                                         $SloKJV$format/41_MAT.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Matej/g"                                                           $SloKJV$format/41_MAT.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Mt/g"                                                              $SloKJV$format/41_MAT.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Evangelij po Sv. Mateju/g"                                           $SloKJV$format/41_MAT.usfm

# MRK
  sed -i "s/\\\\h  /\x5ch Mr/g"                                                                  $SloKJV$format/42_MRK.usfm
  sed -i "s/\\\\h1/\x5ch1 Evangelij po Svetem Marku/g"                                           $SloKJV$format/42_MRK.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Evangelij po Svetem Marku/g"                                       $SloKJV$format/42_MRK.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Marko/g"                                                           $SloKJV$format/42_MRK.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Mr/g"                                                              $SloKJV$format/42_MRK.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Evangelij po Svetem Marku/g"                                         $SloKJV$format/42_MRK.usfm

# LUK
  sed -i "s/\\\\h  /\x5ch Lk/g"                                                                  $SloKJV$format/43_LUK.usfm
  sed -i "s/\\\\h1/\x5ch1 Evangelij po Sv. Luku/g"                                               $SloKJV$format/43_LUK.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Evangelij po Sv. Luku/g"                                           $SloKJV$format/43_LUK.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Luka/g"                                                            $SloKJV$format/43_LUK.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Lk/g"                                                              $SloKJV$format/43_LUK.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Evangelij po Sv. Luku/g"                                             $SloKJV$format/43_LUK.usfm

# JHN
  sed -i "s/\\\\h  /\x5ch Jn/g"                                                                  $SloKJV$format/44_JHN.usfm
  sed -i "s/\\\\h1/\x5ch1 Evangelij po Sv. Janezu/g"                                             $SloKJV$format/44_JHN.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Evangelij po Sv. Janezu/g"                                         $SloKJV$format/44_JHN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Janez/g"                                                           $SloKJV$format/44_JHN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jn/g"                                                              $SloKJV$format/44_JHN.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Evangelij po Sv. Janezu/g"                                           $SloKJV$format/44_JHN.usfm

# ACT
  sed -i "s/\\\\h  /\x5ch Apd/g"                                                                 $SloKJV$format/45_ACT.usfm
  sed -i "s/\\\\h1/\x5ch1 Apostolska dela/g"                                                     $SloKJV$format/45_ACT.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Apostolska dela/g"                                                 $SloKJV$format/45_ACT.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Apostolska dela/g"                                                 $SloKJV$format/45_ACT.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Apd/g"                                                             $SloKJV$format/45_ACT.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Apostolska dela/g"                                                   $SloKJV$format/45_ACT.usfm

# ROM
  sed -i "s/\\\\h  /\x5ch Rim/g"                                                                 $SloKJV$format/46_ROM.usfm
  sed -i "s/\\\\h1/\x5ch1 Poslanica apostola Pavla Rimljanom/g"                                  $SloKJV$format/46_ROM.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Poslanica apostola Pavla Rimljanom/g"                              $SloKJV$format/46_ROM.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Rimljanom/g"                                                       $SloKJV$format/46_ROM.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Rim/g"                                                             $SloKJV$format/46_ROM.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Poslanica apostola Pavla Rimljanom/g"                                $SloKJV$format/46_ROM.usfm

# 1CO
  sed -i "s/\\\\h  /\x5ch 1 Kor/g"                                                               $SloKJV$format/47_1CO.usfm
  sed -i "s/\\\\h1/\x5ch1 Prva poslanica apostola Pavla Korinčanom/g"                            $SloKJV$format/47_1CO.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Prva poslanica apostola Pavla Korinčanom/g"                        $SloKJV$format/47_1CO.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Korinčanom/g"                                                    $SloKJV$format/47_1CO.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Ko/g"                                                             $SloKJV$format/47_1CO.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Prva poslanica apostola Pavla Korinčanom/g"                          $SloKJV$format/47_1CO.usfm

# 2CO
  sed -i "s/\\\\h  /\x5ch 2 Kor/g"                                                               $SloKJV$format/48_2CO.usfm
  sed -i "s/\\\\h1/\x5ch1 Druga poslanica apostola Pavla Korinčanom/g"                           $SloKJV$format/48_2CO.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Druga poslanica apostola Pavla Korinčanom/g"                       $SloKJV$format/48_2CO.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Korinčanom/g"                                                    $SloKJV$format/48_2CO.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Ko/g"                                                             $SloKJV$format/48_2CO.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Druga poslanica apostola Pavla Korinčanom/g"                         $SloKJV$format/48_2CO.usfm

# GAL
  sed -i "s/\\\\h  /\x5ch Gal/g"                                                                 $SloKJV$format/49_GAL.usfm
  sed -i "s/\\\\h1/\x5ch1 Poslanica apostola Pavla Galačanom/g"                                  $SloKJV$format/49_GAL.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Poslanica apostola Pavla Galačanom/g"                              $SloKJV$format/49_GAL.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Galačanom/g"                                                       $SloKJV$format/49_GAL.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Gal/g"                                                             $SloKJV$format/49_GAL.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Poslanica apostola Pavla Galačanom/g"                                $SloKJV$format/49_GAL.usfm

# EPH
  sed -i "s/\\\\h  /\x5ch Ef/g"                                                                  $SloKJV$format/50_EPH.usfm
  sed -i "s/\\\\h1/\x5ch1 Poslanica apostola Pavla Efežanom/g"                                   $SloKJV$format/50_EPH.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Poslanica apostola Pavla Efežanom/g"                               $SloKJV$format/50_EPH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Efežanom/g"                                                        $SloKJV$format/50_EPH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Ef/g"                                                              $SloKJV$format/50_EPH.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Poslanica apostola Pavla Efežanom/g"                                 $SloKJV$format/50_EPH.usfm

# PHP
  sed -i "s/\\\\h  /\x5ch Flp/g"                                                                 $SloKJV$format/51_PHP.usfm
  sed -i "s/\\\\h1/\x5ch1 Poslanica apostola Pavla Filipljanom/g"                                $SloKJV$format/51_PHP.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Poslanica apostola Pavla Filipljanom/g"                            $SloKJV$format/51_PHP.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Filipljanom/g"                                                     $SloKJV$format/51_PHP.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Flp/g"                                                             $SloKJV$format/51_PHP.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Poslanica apostola Pavla Filipljanom/g"                              $SloKJV$format/51_PHP.usfm

# COL
  sed -i "s/\\\\h  /\x5ch Kol/g"                                                                 $SloKJV$format/52_COL.usfm
  sed -i "s/\\\\h1/\x5ch1 Poslanica apostola Pavla Kološanom/g"                                  $SloKJV$format/52_COL.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Poslanica apostola Pavla Kološanom/g"                              $SloKJV$format/52_COL.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Kološanom/g"                                                       $SloKJV$format/52_COL.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Kol/g"                                                             $SloKJV$format/52_COL.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Poslanica apostola Pavla Kološanom/g"                                $SloKJV$format/52_COL.usfm

# 1TH
  sed -i "s/\\\\h  /\x5ch 1 Tes/g"                                                               $SloKJV$format/53_1TH.usfm
  sed -i "s/\\\\h1/\x5ch1 Prva poslanica apostola Pavla Tesaloničanom/g"                         $SloKJV$format/53_1TH.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Prva poslanica apostola Pavla Tesaloničanom/g"                     $SloKJV$format/53_1TH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Tesaloničanom/g"                                                 $SloKJV$format/53_1TH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Te/g"                                                             $SloKJV$format/53_1TH.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Prva poslanica apostola Pavla Tesaloničanom/g"                       $SloKJV$format/53_1TH.usfm

# 2TH
  sed -i "s/\\\\h  /\x5ch 2 Tes/g"                                                               $SloKJV$format/54_2TH.usfm
  sed -i "s/\\\\h1/\x5ch1 Druga poslanica apostola Pavla Tesaloničanom/g"                        $SloKJV$format/54_2TH.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Druga poslanica apostola Pavla Tesaloničanom/g"                    $SloKJV$format/54_2TH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Tesaloničanom/g"                                                 $SloKJV$format/54_2TH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Te/g"                                                             $SloKJV$format/54_2TH.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Druga poslanica apostola Pavla Tesaloničanom/g"                      $SloKJV$format/54_2TH.usfm

# 1TI
  sed -i "s/\\\\h  /\x5ch 1 Tim/g"                                                               $SloKJV$format/55_1TI.usfm
  sed -i "s/\\\\h1/\x5ch1 Prva poslanica apostola Pavla Timóteju/g"                              $SloKJV$format/55_1TI.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Prva poslanica apostola Pavla Timóteju/g"                          $SloKJV$format/55_1TI.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Timóteju/g"                                                      $SloKJV$format/55_1TI.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Ti/g"                                                             $SloKJV$format/55_1TI.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Prva poslanica apostola Pavla Timóteju/g"                            $SloKJV$format/55_1TI.usfm

# 2TI
  sed -i "s/\\\\h  /\x5ch 2 Tim/g"                                                               $SloKJV$format/56_2TI.usfm
  sed -i "s/\\\\h1/\x5ch1 Druga poslanica apostola Pavla Timóteju/g"                             $SloKJV$format/56_2TI.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Druga poslanica apostola Pavla Timóteju/g"                         $SloKJV$format/56_2TI.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Timóteju/g"                                                      $SloKJV$format/56_2TI.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Ti/g"                                                             $SloKJV$format/56_2TI.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Druga poslanica apostola Pavla Timóteju/g"                           $SloKJV$format/56_2TI.usfm

# TIT
  sed -i "s/\\\\h  /\x5ch Tit/g"                                                                 $SloKJV$format/57_TIT.usfm
  sed -i "s/\\\\h1/\x5ch1 Poslanica apostola Pavla Titu/g"                                       $SloKJV$format/57_TIT.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Poslanica apostola Pavla Titu/g"                                   $SloKJV$format/57_TIT.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Titu/g"                                                            $SloKJV$format/57_TIT.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Tit/g"                                                             $SloKJV$format/57_TIT.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Poslanica apostola Pavla Titu/g"                                     $SloKJV$format/57_TIT.usfm

# PHM
  sed -i "s/\\\\h  /\x5ch Fil/g"                                                                 $SloKJV$format/58_PHM.usfm
  sed -i "s/\\\\h1/\x5ch1 Poslanica apostola Pavla Filemonu/g"                                   $SloKJV$format/58_PHM.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Poslanica apostola Pavla Filemonu/g"                               $SloKJV$format/58_PHM.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Filemonu/g"                                                        $SloKJV$format/58_PHM.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Fil/g"                                                             $SloKJV$format/58_PHM.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Poslanica apostola Pavla Filemonu/g"                                 $SloKJV$format/58_PHM.usfm

# HEB
  sed -i "s/\\\\h  /\x5ch Heb/g"                                                                 $SloKJV$format/59_HEB.usfm
  sed -i "s/\\\\h1/\x5ch1 Poslanica apostola Pavla Hebrejcem/g"                                  $SloKJV$format/59_HEB.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Poslanica apostola Pavla Hebrejcem/g"                              $SloKJV$format/59_HEB.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Hebrejcem/g"                                                       $SloKJV$format/59_HEB.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Heb/g"                                                             $SloKJV$format/59_HEB.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Poslanica apostola Pavla Hebrejcem/g"                                $SloKJV$format/59_HEB.usfm

# JAS
  sed -i "s/\\\\h  /\x5ch Jak/g"                                                                 $SloKJV$format/60_JAS.usfm
  sed -i "s/\\\\h1/\x5ch1 Splošno Jakobovo pismo/g"                                              $SloKJV$format/60_JAS.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Splošno Jakobovo pismo/g"                                          $SloKJV$format/60_JAS.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Jakob/g"                                                           $SloKJV$format/60_JAS.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jak/g"                                                             $SloKJV$format/60_JAS.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Splošno Jakobovo pismo/g"                                            $SloKJV$format/60_JAS.usfm

# 1PE
  sed -i "s/\\\\h  /\x5ch 1 Pet/g"                                                               $SloKJV$format/61_1PE.usfm
  sed -i "s/\\\\h1/\x5ch1 Prva splošna Petrova poslanica/g"                                      $SloKJV$format/61_1PE.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Prva splošna Petrova poslanica/g"                                  $SloKJV$format/61_1PE.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Peter/g"                                                         $SloKJV$format/61_1PE.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Pt/g"                                                             $SloKJV$format/61_1PE.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Prva splošna Petrova poslanica/g"                                    $SloKJV$format/61_1PE.usfm

# 2PE
  sed -i "s/\\\\h  /\x5ch 2 Pet/g"                                                               $SloKJV$format/62_2PE.usfm
  sed -i "s/\\\\h1/\x5ch1 Druga splošna Petrova poslanica/g"                                     $SloKJV$format/62_2PE.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Druga splošna Petrova poslanica/g"                                 $SloKJV$format/62_2PE.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Peter/g"                                                         $SloKJV$format/62_2PE.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Pt/g"                                                             $SloKJV$format/62_2PE.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Druga splošna Petrova poslanica/g"                                   $SloKJV$format/62_2PE.usfm

# 1JN
  sed -i "s/\\\\h  /\x5ch 1 Jn/g"                                                                $SloKJV$format/63_1JN.usfm
  sed -i "s/\\\\h1/\x5ch1 Prva splošna Janezova poslanica/g"                                     $SloKJV$format/63_1JN.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Prva splošna Janezova poslanica/g"                                 $SloKJV$format/63_1JN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Janez/g"                                                         $SloKJV$format/63_1JN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Jn/g"                                                             $SloKJV$format/63_1JN.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Prva splošna Janezova poslanica/g"                                   $SloKJV$format/63_1JN.usfm

# 2JN
  sed -i "s/\\\\h  /\x5ch 2 Jn/g"                                                                $SloKJV$format/64_2JN.usfm
  sed -i "s/\\\\h1/\x5ch1 Druga Janezova poslanica/g"                                            $SloKJV$format/64_2JN.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Druga Janezova poslanica/g"                                        $SloKJV$format/64_2JN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Janez/g"                                                         $SloKJV$format/64_2JN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Jn/g"                                                             $SloKJV$format/64_2JN.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Druga Janezova poslanica/g"                                          $SloKJV$format/64_2JN.usfm

# 3JN
  sed -i "s/\\\\h  /\x5ch 3 Jn/g"                                                                $SloKJV$format/65_3JN.usfm
  sed -i "s/\\\\h1/\x5ch1 Tretja Janezova poslanica/g"                                           $SloKJV$format/65_3JN.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Tretja Janezova poslanica/g"                                       $SloKJV$format/65_3JN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 3 Janez/g"                                                         $SloKJV$format/65_3JN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 3Jn/g"                                                             $SloKJV$format/65_3JN.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Tretja Janezova poslanica/g"                                         $SloKJV$format/65_3JN.usfm

# JUD
  sed -i "s/\\\\h  /\x5ch Jud/g"                                                                 $SloKJV$format/66_JUD.usfm
  sed -i "s/\\\\h1/\x5ch1 Judova splošna poslanica/g"                                            $SloKJV$format/66_JUD.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Judova splošna poslanica/g"                                        $SloKJV$format/66_JUD.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Juda/g"                                                            $SloKJV$format/66_JUD.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jud/g"                                                             $SloKJV$format/66_JUD.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Judova splošna poslanica/g"                                          $SloKJV$format/66_JUD.usfm

# REV
  sed -i "s/\\\\h /\x5ch Raz/g"                                                                  $SloKJV$format/67_REV.usfm
  sed -i "s/\\\\h1/\x5ch1 Božansko razodetje Sv. Janeza/g"                                       $SloKJV$format/67_REV.usfm
  sed -i "s/\\\\toc1/\x5ctoc1 Božansko razodetje Sv. Janeza/g"                                   $SloKJV$format/67_REV.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Razodetje/g"                                                       $SloKJV$format/67_REV.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Raz/g"                                                             $SloKJV$format/67_REV.usfm
  sed -i "s/\\\\mt1/\x5cmt1 Božansko razodetje Sv. Janeza/g"                                     $SloKJV$format/67_REV.usfm


echo -E "   --==     Fajl od Psalmov popravi da doda prazno vrstico pred psalme ki imajo naslov ==--"
sed -i "s|\\\v 1 \\\d|\\\d|g"                                                                    $SloKJV$format/19_PSA.usfm
sed -i "s|XXYYmt2XX|\n\\\q1\n\\\p\n\\\v 1|g"                                                     $SloKJV$format/19_PSA.usfm


	# C:\Program Files\PTXprint\PTXprint.exe" -c Diglot XYZ
	# will OPEN PTXprint with XYZ project active and the saved configuration called "Diglot" (but won't print anything)
	#
	# "C:\Program Files\PTXprint\PTXprint.exe" -c NTandPsalms -P XYZ
	# will directly create/PRINT a PDF from the XYJ project using the saved configuration called "NTandPsalms" (no GUI will appear)
	#
	# "C:\Program Files\PTXprint\PTXprint.exe" -b ROM -c SideXrefs -P XYZ
	# will directly create a PDF of the BOOK of ROMANS from the XYJ project using the saved configuration called "SideXrefs" (no GUI will appear)
	#
	# "C:\Program Files\PTXprint\PTXprint.exe" -b "MAT MRK LUK JHN ACT GLO" -P XYZ
	# will directly create a PDF of 4 gospels, Acts and Glossary from the XYJ project using the Default configuration (no GUI will appear)
	#
	# "C:\Program Files\PTXprint\PTXprint.exe" -d "C:\Temp"
	# runs PTXprint, and output PDF files will be created in C:\Temp folder instead of C:\My Paratext 9 Projects\<XYZ>\local\ptxprint
	#
	# From your example, it looks like you are trying to load a particular project from a specific location, and using -p to provide the Path to Paratext Projects directory. Note that this needs to point to the PARENT path of one or more Paratext/USFM project folders. So, for example, on a Windows system, -p is usually pointing to "C:\My Paratext 9 Projects" under which there are several PROJECT folders (in which the USFM files reside).
	#
	# So perhaps what you need to enter is:
	#
	# ptxprint -p /home/pc/Dokumenti/osos2usfm/SloKJV/release/ XYZ 
	#
	# where XYZ is replaced by the Project Name/Code.


#============= Doda STARA ZAVEZA in NOVA ZAVEZA  ==============
echo -E "   --==  Doda STARA ZAVEZA in NOVA ZAVEZA  in page break med Staro in Novo zavezo  ==--"
# Gleda na string   \mt1 Prva Mojzesova knjiga
sed -i "s|\(\\\mt1 Prva Mojzesova knjiga\)|\\\pb\\\mt1 STARA ZAVEZA\n\\\b\\\b\1|g"           $SloKJV$format/01_GEN.usfm
# Gleda na string   udarim zemlje s prekletstvom.«
sed -i "s|\(\\\toc3 Mt\)|\1\n\\\pb\n\\\mt1 NOVA ZAVEZA\n\\\b \n|g"                           $SloKJV$format/41_MAT.usfm
#==============================================================

#========== Popravi ALEF ===============
sed -i "s|\(\\\c 119\)|\1\n\\\qa ALEF א|g"                                                   $SloKJV$format/19_PSA.usfm
cat $SloKJV$format/19_PSA.usfm |grep -2 "ALEF"
#========================================

#===========  PTXPRINT  ============================
echo -E "   --==  ptxprint -c /home/pc/Dokumenti/osis2usfm/SloKJV/release SloKJV_A4 ==--"
echo              ptxprint -c /home/pc/Dokumenti/osis2usfm/SloKJV/release SloKJV_$format
echo .
ptxprint -c       /home/pc/Dokumenti/osis2usfm/SloKJV/release SloKJV_$format
#====================================================


#===========  Spredaj doda 6 A4 strani SloKJV PDF-ju  =======================================
echo -E "   --==  Spredaj doda 6 A4 strani SloKJV PDF-ju ==--"
echo "   pdfunite $osis2usfm/SloKJV_"$format"_prvi_del_knjige.pdf $SloKJV$format/local/ptxprint/SloKJV_"$format"_Default_GEN-REV_ptxp.pdf $SloKJV_Github/SloKJV_"$format"_dva_stolpca.pdf"
#============================================================================================
#  Ce je Samo nova zaveza se fajl drugace imenuje    ...MAT-REV_ptxp.pdf

     case $format in
          "A5_NZ")
              echo " "
              echo "   Samo Nova zaveza ..."
              echo " "
              pdfunite $osis2usfm/SloKJV_"$format"_prvi_del_knjige.pdf $SloKJV$format/local/ptxprint/SloKJV_"$format"_Default_MAT-REV_ptxp.pdf $SloKJV_Github/SloKJV_"$format"_dva_stolpca.pdf
              exit
              ;;
          *)  echo "  Celotno Sveto pismo ... "
              pdfunite $osis2usfm/SloKJV_"$format"_prvi_del_knjige.pdf $SloKJV$format/local/ptxprint/SloKJV_"$format"_Default_GEN-REV_ptxp.pdf $SloKJV_Github/SloKJV_"$format"_dva_stolpca.pdf
              ;;
     esac
#=============================================================================================


#============ Pozene GITHUB Desktop? ========================
echo " "
echo "   Pozene GITHUB Desktop?"
echo " "
PS5='   Izberi: '
options_ver=("Ne" "Pozene" "Izhod")
select opt_ver in "${options_ver[@]}"
do
      case $opt_ver in
          "Ne")
              echo " "
              echo "   Pa drugic sinhronizacija z Githubom."
              echo " "
              break
             ;;
          "Pozene")
              echo " "
              echo "   Izbral si nadgraditev."
              echo " "
              echo "     Sinhronizacija z Githubom ..."
              echo " "
              echo "   --==  Pozene /usr/bin/github-desktop ==--"
                #================================================================================
                echo -E "  Ocisti mape zacasnih datotek..."
                find $SloKJV_Github/PTXprint -name '*.usfm' -exec rm {} \;        >/dev/null 2>&1
                find $SloKJV_Github/PTXprint -name 'local'  -exec rm -rf {} \;    >/dev/null 2>&1
                #================================================================================
              /usr/bin/github-desktop
              break
              ;;
          "Izhod")
              echo " "
              echo "   Izbral si $REPLY kar je $opt_ver"
              echo " "
              exit
             ;;
          *) echo "Napacna izbira $REPLY";;
     esac
done
#====================================================
