#!/bin/bash
 
# Set paths
  SloKJVepubPath=/home/pc/Dokumenti/epub
       osis2usfm=/home/pc/Dokumenti/GitHub/SloKJV/PTXprint/osis2usfm
   SloKJV_Github=/home/pc/Dokumenti/GitHub/SloKJV
          SloKJV=/home/pc/Dokumenti/GitHub/SloKJV/PTXprint/osis2usfm/SloKJV/release/SloKJV_
          format=US_Trade

# Naredi mapo release in mapo projekta
mkdir $osis2usfm/SloKJV/release                >/dev/null 2>&1
mkdir $osis2usfm/SloKJV/release/SloKJV_$format >/dev/null 2>&1

# Prestavi se v mapo   osis2usfm=/home/pc/Dokumenti/GitHub/SloKJV/PTXprint/osis2usfm
cd $osis2usfm                                  >/dev/null 2>&1


# Ko kreiras novo knjigo je potrebno vnesti v ptxSettings.xml
#    <ChapterVerseSeparator>,</ChapterVerseSeparator>                  # ta je pomemben, ker se doloci locilo med vrstico in poglavjem!
#    <RangeIndicator>-</RangeIndicator>
#    <SequenceIndicator>.</SequenceIndicator>
#    <ChapterRangeSeparator>–</ChapterRangeSeparator>
#    <BookSequenceSeparator>; </BookSequenceSeparator>
#    <ChapterNumberSeparator>; </ChapterNumberSeparator>

# ================== Videti je takole: ptxSettings.xml =========================================================
#/home/pc/Dokumenti/GitHub/SloKJV/PTXprint/osis2usfm/SloKJV/release/SloKJV_A4/ptxSettings.xml  
#<ScriptureText><Name>SloKJV</Name>
#    <Language>Slovene</Language>
#    <Encoding>65001</Encoding>
#    <Copyright></Copyright>
#    <DefaultFont>Linux Libertine O</DefaultFont>
#    <DefaultFontSize>10</DefaultFontSize>
#    <FileNamePostPart>.usfm</FileNamePostPart>
#    <FileNameBookNameForm>41_MAT</FileNameBookNameForm>
#    <ChapterVerseSeparator>,</ChapterVerseSeparator>
#    <RangeIndicator>-</RangeIndicator>
#    <SequenceIndicator>.</SequenceIndicator>
#    <ChapterRangeSeparator>–</ChapterRangeSeparator>
#    <BookSequenceSeparator>; </BookSequenceSeparator>
#    <ChapterNumberSeparator>; </ChapterNumberSeparator>
#    <FileNamePrePart />
#    <MinParatextVersion>8.0.63.1</MinParatextVersion>
#    <FullName>Sveto pismo kralja Jakoba (1769)</FullName>
#    <Editable>F</Editable>
#    <BooksPresent>1111111111111111111111111111111111111110111111111111111111111111111111111000000000000000000000000000000000000000000000000000</BooksPresent>
#</ScriptureText>
# =============================================================================================================================================================


                          #  A4        210 x 297 mm
                          #  A5        148 x 210 mm
                          #  US Trade  152 x 229 mm


# Function to check if a key is pressed
key_pressed_brisanje_temp_files() {
    read -t 2 -n 1 key
    if [ $? -eq 0 ]; then
        echo "   Brisanje datotek ...."
		#======== Pobrise vse  *pdf  in  *.usfm  datoteke =====
		echo  "    Pobrise vse pdf datoteke ..."
		echo  "      Ostaja samo *.USFM v KJV mapi ..."
		cd $osis2usfm
		#find $osis2usfm/SloKJV/release . -type f -name "*.pdf"  -exec ls {} +
		find $osis2usfm/SloKJV/release  . -type f -name "*.pdf"  -exec rm {} +
		find $osis2usfm/SloKJV/release  . -type f -name "*.usfm" -exec ls {} +
		find $osis2usfm/SloKJV/release  . -type f -name "*.usfm" -exec rm {} +
		echo  "      Pobrise vse fajle v mapah local ..."
		find $osis2usfm/SloKJV/release -type d -name 'local' -exec find '{}' -type f -iname '*' -print -delete ';'
		# find $osis2usfm/SloKJV/release -type d -name 'local' -exec find '{}' -type f -iname '*' -print ';'
		#=======================================================
    else
        echo "   Nadaljujem ...."
    fi
}


#======= zberi velikost PDF verzije SloKJV =============
echo "   Izberi velikost PDF verzije SloKJV"
echo -E "   "
PS3='Izberi velikost PDF verzije SloKJV: '
options=("Test" "A4" "US_Trade" "A5" "A5_NZ_BIG" "A5_NZ_Ps" "A5_NZ_prostor" "SLO-KJV" "FRTLOCAL_SFM" "PTXPRINT_STY" "PTXPRINT_CFG" "BrisanjeTemp" "Izhod")
select opt in "${options[@]}"
do
    case $opt in
        "Test")
            echo "   Izbral si: Test."
            format=Test
            break
            ;;
        "A4")
            echo "   Izbral si: A4."
            format=A4
            break
            ;;
        "US_Trade")
            echo "   Izbral si: US_Trade."
            format=US_Trade
            break
            ;;
        "A5")
            echo "   Izbral si: A5."
            format=A5
            break
            ;;
        "A5_NZ_BIG")
            echo "   Izbral si: A5_NZ_BIG."
            format=A5_NZ_BIG
            break
            ;;
        "A5_NZ_Ps")
            echo "   Izbral si: A5_NZ_Ps."
            format=A5_NZ_Ps
            break
            ;;
        "A5_NZ_prostor")
            echo "   Izbral si: A5_NZ_prostor."
            format=A5_NZ_prostor
            break
            ;;
        "SLO-KJV")
            echo "   Izbral si: SLO-KJV."
            format=SLO-KJV
            break
            ;;
        "FRTLOCAL_SFM")
            echo "   Izbral si: Urejanje FRTlocal.sfm datotek."
            format=FRTLOCAL_SFM
            find SloKJV/ -type f -name "FRTlocal.sfm" -exec pico {} \;
            break
            ;;
        "PTXPRINT_STY")
            echo "   Izbral si: Urejanje ptxprint.sty datotek."
            format=PTXPRINT_STY
            find SloKJV/ -type f -name "ptxprint.sty" -exec pico {} \;
            break
            ;;
        "PTXPRINT_CFG")
            echo "   Izbral si: Urejanje ptxprint.cfg datotek."
            format=PTXPRINT_STY
            find SloKJV/ -type f -name "ptxprint.cfg" -exec pico {} \;
            break
            ;;
        "BrisanjeTemp")
            echo "   Izbral si Brisanje Temp datotek $opt"
            echo "   Pritisni tipko za brisanje začasnih PTXprint datotek ..."
            #= === Vklop in izklop čakanja ===
            key_pressed_brisanje_temp_files
            #=================================
            echo "key..."
            exit
            ;;
        "Izhod")
            echo "   Izbral si $REPLY kar je $opt"
            exit
            ;;
        *) echo "Napacna izbira $REPLY";;
    esac
done
#===================================================


#============== Kreira mapo z izbrano velikostjo PDF datoteke. ========================
      case $format in
           "FRTLOCAL_SFM")
               echo "   Preskoci kreiranje mape."
               ;;
           "PTXPRINT_STY")
               echo "   Preskoci kreiranje mape."
               ;;
           *)  echo "   Kreira mapo."
               mkdir $SloKJV_Github/PTXprint/osis2usfm/SloKJV/release/SloKJV_$format  2>/dev/null
               ;;
      esac
#=============================================================================================


# Naredi simbolicen link iz Github na mapo osis2usfm (samo prvic)
#ln -s $SloKJV_Github/PTXprint/osis2usfm/run_osis2usfm $osis2usfm       2>/dev/null
#ln -s $SloKJV_Github/PTXprint/osis2usfm/osis2usfm.py $osis2usfm        2>/dev/null
#ln -s $SloKJV_Github/PTXprint/osis2usfm/SloKJV/ $osis2usfm             2>/dev/null


#================ PTXPrint nadgradi na zadnjo verzijo? ====================
echo " "
echo "   Ali se PTXPrint nadgradi na zadnjo verzijo?"
echo " "
PS3='   Izberi: '
options_ver=("Ne" "Nadgradi" "Izhod")
 select opt_ver in "${options_ver[@]}"
 do
     case $opt_ver in
         "Ne")
             echo " "
             echo "   --==   Pa drugic nadgradnja PTXprint...."
             echo " "
             break
             ;;
         "Nadgradi")
             echo " "
             echo "   Izbral si nadgraditev."
             echo " "
             echo "     Ubuntu package ptxprint update ..."
             echo " "
                 sudo add-apt-repository ppa:silnrsi/ptxprint
                 sudo apt update
                 sudo apt install python3-ptxprint
             break
             ;;
         "Izhod")
             echo " "
             echo "Izbral si $REPLY kar je $opt_ver"
             echo " "
             exit
             ;;
         *) echo "Napacna izbira $REPLY";;
     esac
 done
#==========================================================================


# Potegne iz Githuba (po zelji izklopi ko ni interneta)
#https_proxy=http://proxy.gov.si:80/
#wget --no-proxy https://github.com/msavli/SloKJV/raw/master/SloKJV_sword.xml -O $osis2usfm/SloKJV_sword.xml


#============ Pozene GITHUB Desktop? ========================
echo " "
echo "   Pozene GITHUB Desktop?"
echo " "
PS5='   Izberi: '
options_ver_Git=("Ne" "Pozene" "Izhod")
select opt_ver_Git in "${options_ver_Git[@]}"
 do
      case $opt_ver_Git in
          "Ne")
              echo -e " "
              echo -e "   --==    Pa drugic sinhronizacija z Githubom."
              echo -e " "
              break
             ;;
          "Pozene")
              echo " "
              echo "   Izbral si nadgraditev."
              echo " "
              echo "     Sinhronizacija z Githubom ..."
              echo " "
                #================================================================================
                echo -E "   Ocisti mapo $format zacasnih datotek..."
                #  SloKJV_Github=/home/pc/Dokumenti/GitHub/SloKJV
                find $SloKJV_Github/PTXprint/osis2usfm/SloKJV/release/SloKJV_* -name '*.usfm'     -exec rm {} \;        >/dev/null 2>&1
                find $SloKJV_Github/PTXprint/osis2usfm/SloKJV/release/SloKJV_* -name '*.usfm.adj' -exec rm {} \;        >/dev/null 2>&1
                find $SloKJV_Github/PTXprint/osis2usfm/SloKJV/release/SloKJV_* -name 'local'      -exec rm -rf {} \;    >/dev/null 2>&1
                #================================================================================
              /usr/bin/github-desktop
              break
              ;;
          "Izhod")
              echo " "
              echo "   Izbral si $REPLY kar je $opt_ver"
              echo " "
              exit
             ;;
          *) echo "Napacna izbira $REPLY";;
     esac
 done
#==========================================================================


cd $osis2usfm

# Potegne iz lokanega Githuba (hitreje)
cp $SloKJV_Github/SloKJV_sword.xml  $osis2usfm/SloKJV_sword.xml


# =============== Potegne gor vrstice k stevilki verza ====================
sed -i ':a;N;$!ba;s/\">\n/\"> /g'                     $osis2usfm/SloKJV_sword.xml
sed -i ':a;N;$!ba;s/\"\/>\n/\"\/> /g'                 $osis2usfm/SloKJV_sword.xml
#         Sedaj lepo izgleda koda...
#                  sed ':a;N;$!ba;s/\n/ /g' file
#
#                       :a create a label 'a'
#                          N append the next line to the pattern space
#                            $! if not the last line, ba branch (go to) label 'a'
#                                 s substitute, /\n/ regex for new line, / / by a space, /g global match (as many times as it can)
#
#         Še Psalme potegne naslove gor
#                <title type="chapter">Psalm 3</title>
#           <title type="psalm" canonical="true">
sed -i ':a;N;$!ba;s/<title type=\"chapter\">Psalm \([0-9]*\)<\/title>\n              <title type=\"psalm\" canonical=\"true\">/<title type=\"chapter\">Psalm \1<\/title><title type=\"psalm\" canonical=\"true\">/g'                 $osis2usfm/SloKJV_sword.xml
cat $osis2usfm/SloKJV_sword.xml |grep "<title><title type="
# =========================================================================


# ================ Uredi odstavke =============
echo -E "   --==    Uredi odstavke                                                "
echo -E "   --==    <milestone type=\"x-p\" marker=\"¶ \"/>                       "
echo -E "   --==    <milestone type=\"x-p\" subType=\"x-added\" marker=\"¶\"/>    "
echo -E "   --==    \p                                                            "
sed -i "s|<milestone type=\"x-p\" marker=\"¶ \"/>| \x5cp|g"                       $osis2usfm/SloKJV_sword.xml
sed -i "s|<milestone type=\"x-p\" subType=\"x-added\" marker=\"¶\"/>| \x5cp|g"    $osis2usfm/SloKJV_sword.xml
cat $osis2usfm/SloKJV_sword.xml |grep "milestone"
# =============================================


# =================== DODANE BESEDE ITALIC JEZUS ========================
echo -E "   --==    Kjer je italic vgnezden v Jezusovih besedah..."
#  <transChange type="added">nekaj</transChange>          ->     \+add nekaj\+add* 
#
# Run the Python script
python3 zamenjaj_added.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
#cat $osis2usfm/SloKJV_sword.xml |grep "gospodar naredil za vladarja nad njegovo dru"
#cat $osis2usfm/SloKJV_sword.xml |grep "To je moje telo"
#cat $osis2usfm/SloKJV_sword.xml |grep "tako se nama spodobi"
echo -E " "
# ======================================================================


# ======= Zamenja DIVINE NAME GOSPOD ===============
echo -E "   --==    Zamenja DIVINE NAME GOSPOD"
# Write a Python script to change <divineName>Gospod</divineName> to \\+nd Gospod\\+nd if it is between Jesus speaking tags, and to \\nd Gospod\\nd if it is not between Jesus speaking tags. 
# Do the same if the <divineName> tag is inside an <inscription> tag
python3 zamenjaj_DivineName.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep "Bog je Mojzesu spregovoril in mu rekel: »Jaz"
# cat $osis2usfm/SloKJV_sword.xml |grep "Človek je sklonil svojo glavo"
# cat $osis2usfm/SloKJV_sword.xml |grep "mojemu Gospodu: ›Sédi na mojo"
# cat $osis2usfm/SloKJV_sword.xml |grep "istega zlata in nanjo napisali pisanje"
echo -E "  "
# ================================================================================


# =================== BOLD v opombi Psalma 22  ========================
echo -E "   --==    BOLD v opombi Psalma 22"
echo -E " "
#               <hi type="bold">   </hi>        ->          \+bd   \+bd*
#
# Run the Python script
python3 zamenjaj_note_study_bold.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep "sposoben leteti in oplodi"
echo -E " "
# ======================================================================


# ============= Zamenjaj NOTE STUDY ================
echo -E "   --==    Zamenja NOTE STUDY"
echo -E " "
# Imamo vrstico
#                 </verse><verse osisID="Matt.4.7"> Jezus mu je rekel: <q who="Jesus" marker="">»Prav tako je pisano: ›Ti<note type="crossReference"><reference osisRef="Deut.6.16">5 Mz 6,16</reference></note> ne boš skušal<note type="study">skušal</note> Gospoda, svojega Boga.‹«</q>
# Če Jezus ne govori 
#     <note type="study">skušal</note>   ->   \f + \fr 4,7: \ft some text\f*
# Če Jezus govori 
# <note type="study">skušal</note>   ->       \+f + \fr 4,7: \+ft some text\f*
# 
python3 zamenjaj_note_study.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
#cat $osis2usfm/SloKJV_sword.xml |grep "Satan odpre usta"
#cat $osis2usfm/SloKJV_sword.xml |grep "Prav tako je pisano:"
# ================================================================================


# ================= Zamenjaj NOTE REFERENCE ================================
echo -E "   --==    Zamenja NOTE REFERENCE"
echo -E " "
python3 zamenjaj_note_reference.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
#cat $osis2usfm/SloKJV_sword.xml |grep "V začetku je Bog ustvaril nebo in zemljo"
#cat $osis2usfm/SloKJV_sword.xml |grep "temveč od vsake besede"
# Odstrani v \ip vrsticah vse reference, ker jih ne podpira USFM
# sed -i "s|||g"                       $osis2usfm/SloKJV_sword.xml
# ================================================================================


# ================= Zamenjaj Odstrani Reference iz uvoda ================================
echo -E "   --==    Zamenjaj Odstrani Reference iz uvoda"
echo -E " "
python3 zamenjaj_note_reference_introduction.py 
cat $osis2usfm/SloKJV_sword.xml |grep "introduction" |grep "reference"
# ================================================================================


# ======= Zamenja Inscription ======================
echo -E "   --==    Zamenja Inscription"
# <inscription>SVETO \+nd Gospodu\+nd*</inscription>   ->   \em SVETO \+nd Gospodu\+nd*\}\em*
python3 zamenjaj_Inscription.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
#   preveri   MENE, MENE, TEKEL, UPHARSIN
cat $osis2usfm/SloKJV_sword.xml |grep -2 "Bog je preštel tvoje kraljestvo in ga konč"
echo -E "  "
# ================================================================================


# ======= Zamenja Jesus ===========================
echo -E "   --==    Zamenja Jesus"
# Verses in the Bible has Jesus speaking tags
# verse osisID="Matt.8.4"> In Jezus mu reče: <q who="Jesus" marker="">»Glej, da nikomur ne poveš, ampak pojdi svojo pot, pokaži se duhovniku in ponudi dar, ki ga je Mojzes\+x \xo 8,4: \xt 3 Mz 14,4 \+x* zapovedal, njim v pričevanje.«</q>
# Change <q who="Jesus" marker="">   to \wj 
# and </q>   to \wj* 
python3 zamenjaj_Jesus.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep "kajti tako se nama spodobi"
echo -E "  "
# ================================================================================


# ================================================================================
echo -E "   --==    Dodaj presledek med opombo in referenco"
sed -i 's/\\f\*\\x/\\f\* \\x/g' $osis2usfm/SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep "spremeniti v obliko nad nečem"
# ================================================================================


# ================================================================================
echo -E "   --==    Dodaj presledek med Jezusovimi besedami in referenco ==--"
#      \wj*\x    ->    \wj* \x
sed -i "s/\\\\wj\*\\\\x/\x5cwj\* \x5cx/g"             $osis2usfm/SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep "Samariji ter do skrajnega dela zemlje"
# ================================================================================


# ======= Kolofon ========================
echo -E "   --==    Zamenja Kolofon"
#</verse></chapter>
#<div type="colophon" osisID="1Tim.c"> [Prvo Timóteju je bilo napisano iz Laodikeje, ki je glavno mesto Frigije Pacatiane.]\f + \fr 6,21: \ft [Frigija: zahodni del izmed dveh frigijskih provinc.]\f*
#</div>
python3 zamenjaj_colophon.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
#cat $osis2usfm/SloKJV_sword.xml |grep -2 "Pacatiane"
#cat $osis2usfm/SloKJV_sword.xml |grep -2 "Rima po Epafroditu"
echo -E "  "
# ================================================================================


# ======= Zamenjaj naslov Psalmov ========================
echo -E "   --==    Zamenja naslov Psalmov"
# Write a Python script to hide the title line in line 1 of Psalms so it can be later extracted. 
# Example: 
#   <title type=“psalm” canonical=“true”> \x \xo 2,12: \xt 2 Sam 15,1-18 \x Davidov psalm, ko je bežal pred svojim sinom Absalomom.</title> 
#   <verse osisID=“Ps.3.1”> \nd Gospod\nd, kako\f + \fr 3,1: \ft [Leta 1023 pr. Kr.]\f* so se okrepili ti, ki me vznemirjajo! Številni \add so\add* tisti, ki se vzdigujejo zoper mene.</verse>
python3 zamenjaj_Psalm_title.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
echo -E "  "
# cat $osis2usfm/SloKJV_sword.xml |grep -2 "je bežal pred svojim sinom Absalomom"
# ================================================================================


# ======= Zamenjaj Psalm 119 Alef ========================
echo -E "   --==    Zamenja Psalm 119 Alef"
#
# <title type="acrostic" canonical="true"><foreign n="א">[ALEF א]</foreign> </title>
#
#   spremeni v
#                  \qa [ALEF א]
#
python3 zamenjaj_Psalm_119_Alef.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
echo -E "  "
#cat $osis2usfm/SloKJV_sword.xml |grep "ALEF"
#cat $osis2usfm/SloKJV_sword.xml |grep "S čim naj mladenič očisti svojo"
#echo -E "  "
# ================================================================================


# ================= Zamenja DIV TYPE BOOK ================================
echo -E "   --==    Zamenja DIV TYPE BOOK    "
echo -E " "
#      Popraviti zaradi python skripta
#           <div type=\"book\" osisID=\"Gen\">  ->   <div type=\"book\">
python3 zamenjaj_div_type_book.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
#cat $osis2usfm/SloKJV_sword.xml |grep "book\"osisID="
#cat $osis2usfm/SloKJV_sword.xml |grep "Knjiga Psalmov"
#=============================================================


# ================= DIV TYPE BOOKGROUP ================================
echo -E "   --==    DIV TYPE BOOKGROUP    "
echo -E " "
#      Popraviti zaradi python skripta
#    <div type=\"bookGroup\" subType=\"x-OT\" canonical=\"true\">   ->    <div type=\"x-testament\">
#    <div type=\"bookGroup\" subType=\"x-NT\" canonical=\"true\">   ->    <div type=\"x-testament\">
sed -i "s|<div type=\"bookGroup\" subType=\"x-OT\" canonical=\"true\">|<div type=\"x-testament\">|g"           $osis2usfm/SloKJV_sword.xml
sed -i "s|<div type=\"bookGroup\" subType=\"x-NT\" canonical=\"true\">|<div type=\"x-testament\">|g"           $osis2usfm/SloKJV_sword.xml
cat $osis2usfm/SloKJV_sword.xml |grep "bookGroup"
#=============================================================


# ================= VERSE OSIS ID ODSTRANI ================================
echo -E "   --==    VERSE OSIS ID ODSTRANI (zaradi python skripta)    "
echo -E " "
#      Popraviti zaradi python skripta
#    <verse osisID=\"Gen.1.2\">   ->   <verse>
echo -E " "
sed -i "s|<verse osisID=\"\([^.]*\).\([^.]*\).\([^.]*\)\">|<verse>|g"       $osis2usfm/SloKJV_sword.xml
#cat $osis2usfm/SloKJV_sword.xml |grep -F '<verse osisID=\"Gen.1.2\">'
#cat $osis2usfm/SloKJV_sword.xml |grep "On bo kakor drevo"
#=============================================================


# ================= CHAPTER OSIS ID ODSTRANI ================================
echo -E "   --==    CHAPTER OSIS ID ODSTRANI (zaradi python skripta)    "
echo -E " "
#      Popraviti zaradi python skripta
#          <chapter osisID=\"Gen.01\" chapterTitle=\"1. Poglavje\">   ->   <chapter>
#        <chapter osisID="Job.41" chapterTitle="41. Poglavje">               -//-
#        <chapter osisID="Ps.1" chapterTitle="Psalm 1">                      -//-
python3 zamenjaj_chapter.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep -1 "V začetku je Bog ustvaril nebo"
#cat $osis2usfm/SloKJV_sword.xml |grep -F '<chapter osisID="Gen.01" chapterTitle="1. Poglavje\">'
#cat $osis2usfm/SloKJV_sword.xml |grep -F '<chapter'   # xx
#=============================================================


# ================= Naslovi poglavij ================================
echo -E "   --==    Naslovi poglavij    "
echo -E " "
#      Popraviti zaradi python skripta
#        <title type="chapter">1. Poglavje</title><verse>   ->    <verse>#Start_naslov#1. Poglavje#Konec_naslov#
#
python3 zamenjaj_chapter_naslov.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep "V začetku je Bog ustvaril nebo"
# cat $osis2usfm/SloKJV_sword.xml |grep "In pokazal mi je bistro reko"
#=============================================================


# ================= Uvod shrani v 1. vrstico ================================
echo -E "   --==    Uvod shrani v 1. vrstico     "
echo -E " "
#  Bing AI  Write a Python script to incorporate the introduction line into the verse line. Then change each <lb /> to \ip . Do not forget on input and output file like in previous examples. Example: <div type=“introduction”> <p type=“x-noindent” subType=“x-introduction”>[some_text <lb /> some_text <lb /> some_text.]</p> </div> <chapter><verse> should be changed to <chapter><verse>#Zacetek_Uvoda#[some_text \ip some_text \ip some_text.]#Konec_Uvoda#
#
#      Popraviti zaradi python skripta
#
#         <div type="introduction">         <p type="x-noindent" subType="x-introduction">[Gen <lb /> da bo <lb /> konec.]</p>
#         </div>
#      <chapter><verse>
#
#     Popravi na 
#
#                   <chapter><verse>#Zacetek_Uvoda#[Gen \ip da bo \ip konec.]#Konec_Uvoda#
python3 zamenjaj_uvod_v_1_vrstico.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep -1 "#Zacetek_Uvoda#"
#=============================================================


# ================= Naslov knjige shrani v 1. vrstico ================================
echo -E "   --==    Naslov knjige shrani v 1. vrstico     "
echo -E " "
# Bing AI  Write a Python script to incorporate the title line into the verse line. Do not forget on input and output file like in previous examples. Example: <title type=“main” short=“Geneza”>Prva Mojzesova knjiga, imenovana Geneza</title> <chapter><verse> should be changed to <chapter><verse>#Zacetek_knjige#Prva Mojzesova knjiga, imenovana Geneza#Konec_knjige#
#
#      <title type="main" short="Geneza">Prva Mojzesova knjiga, imenovana Geneza</title>
#       <chapter><verse>
#
#     Popravi na 
#                   <chapter><verse>#Zacetek_knjige#Prva Mojzesova knjiga, imenovana Geneza#Konec_knjige#
#
python3 zamenjaj_naslov_knjige_v_1_vrstico.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep -1 "#Zacetek_knjige#"
#=============================================================


# ================= Staro in Novo zavezo shrani v 1. vrstico ================================
echo -E "   --==    Staro in Novo zavezo shrani v 1. vrstico     "
echo -E " "
#
#       <title type="main">Stara zaveza</title>
#       <div type="book">     <chapter><verse>
#
#     Popravi na 
#                   <div type="book"><chapter><verse>#Zacetek_zaveze#Stara zaveza#Konec_zaveze#
#
python3 zamenjaj_zaveze_knjige_v_1_vrstico.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep -1 "#Zacetek_zaveze#"
#=============================================================


# ================= Ime biblije shrani v 1. vrstico ================================
echo -E "   --==    Ime biblije shrani v 1. vrstico     "
echo -E " "
#     
#       <header>
#           <work osisWork="SloKJV">             <title>Sveto pismo Kralja Jakoba (1769) – SloKJV</title>
#           <creator></creator>
#       </header>
#
#     Popravi na 
#
#                   <div type="x-testament"><div type="book"><chapter><verse>#Zacetek_Ime_Biblije#Sveto pismo Kralja Jakoba (1769) – SloKJV#Konec_ime_Biblije#
#
python3 zamenjaj_ime_biblije_v_1_vrstico.py $osis2usfm/SloKJV_sword.xml $osis2usfm/SloKJV_sword1.xml
mv SloKJV_sword1.xml SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep -1 "#Zacetek_Ime_Biblije#"
# cat $osis2usfm/SloKJV_sword.xml |grep -3 "#Zacetek_zaveze#Nova zaveza#Konec_zaveze#"
#=============================================================


#================== Doda se eno kvazi prazno knjigo ===========
echo -E "   --==    Doda se eno kvazi prazno knjigo da je     Mt  41-ta knjiga namesto 40    "
echo -E " "
#  Doda se eno kvazi prazno knjigo da je     Mt  41-ta knjiga namesto 40
#                                        in  Raz 67-ta knjiga namesto 66 
#       </verse></chapter></div></div>      spremeni v    </verse></chapter></div><div type="book"></div></div>   
sed -i "s|<\/verse><\/chapter><\/div><\/div>|<\/verse><\/chapter><\/div><div type=\"book\"><\/div><\/div>|g"            $osis2usfm/SloKJV_sword.xml
echo -E " "
# cat $osis2usfm/SloKJV_sword.xml |grep -3 "#Zacetek_zaveze#Nova zaveza#Konec_zaveze#"
echo -E " "
#=============================================================


#================== ODSTRANI PRESLEDKE ===================================
echo -E "   --==    ODSTRANI PRESLEDEK...    "
echo -E " "
# Odstrani presledke, enega ali vec, na zacetku vrstic#
sed -i "s/^[ ]*//g"                                      $osis2usfm/SloKJV_sword.xml
# Odstrani presledke, enega ali vec, na koncu vrstic
sed -i 's/ *$//'                                         $osis2usfm/SloKJV_sword.xml
# Odstrani presledek med  <verse> TEXT
sed -i 's/<verse> /<verse>/'                            $osis2usfm/SloKJV_sword.xml
# cat $osis2usfm/SloKJV_sword.xml |grep  -2 "Zlobni bodo na"
#=========================================================================



#=========================================================================
echo -E "   --==    Pozene generiranje usfm datotek==--   "
#=========================================================================
# Pobrise vse prejsnje usfm datoteke
rm /home/pc/Dokumenti/osis2usfm/*.usfm  >/dev/null 2>&1
rm $SloKJV$format/*.usfm >/dev/null 2>&1
# Pobrise vse prejsnje PDF datoteke   in ne izpise napake na ekranu
rm $SloKJV$format/local/ptxprint/*.pdf >/dev/null 2>&1
echo -E " "
echo -E "   python3 osis2usfm.py SloKJV_sword.xml"
echo -E " "
python3 osis2usfm.py SloKJV_sword.xml
# Pobrise 40-to kvazi knjigo da so knjige Nove zaveze pravilno ostevilcene
rm $SloKJV$format/40____.usfm >/dev/null 2>&1
#=========================================================================
#=========================================================================


# ================= Pridobi BibleName iz USFM datoteke  ================================
echo -E "   --==    Naslov knjige shrani v 1. vrstico     "
echo -E " "
#
#  \v 1 #Zacetek_Ime_Biblije#Sveto pismo Kralja Jakoba (1769) – SloKJV#Konec_ime_Biblije##
#
python3 pridobi_BibleName.py 01_GEN.usfm
# cat 00_BibleName.txt
cat 01_GEN.usfm |grep "#Zacetek_Ime_Biblije#"
#=============================================================


# ================= Pridobi Zaveza  ================================
echo -E "   --==    Pridobi Nova Zaveza in Stara Zaveza     "
echo -E " "
#
#  \v 1 #Zacetek_Ime_Biblije#Sveto pismo Kralja Jakoba (1769) – SloKJV#Konec_ime_Biblije##
#
python3 pridobi_Zaveza.py
# cat 00_BibleName.txt
#cat 01_GEN.usfm |head -10
#cat 41_MAT.usfm |head -10
#=============================================================


# ================= Pridobi Naslove knjig  ================================
echo -E "   --==    Pridobi Naslove knjig    "
echo -E " "
#
#  \v 1 #Zacetek_knjige# ...  #Konec_knjige#
#
python3 pridobi_Naslove_Knjig.py
#head -15 cat 01_GEN.usfm
echo -E " "
#head -15 cat 02_EXO.usfm
#=============================================================


# ================= Pridobi Uvode  ================================
echo -E "   --==    Pridobi Uvode    "
echo -E " "
#
#  \v 1 #Zacetek_Uvoda# ....  #Konec_Uvoda#
#
python3 pridobi_Uvode.py
#head -15 cat 01_GEN.usfm
echo -E " "
#head -15 cat 02_EXO.usfm
#=============================================================


# ================= Pridobi Stevilke Psalmov  ================================
echo -E "   --==    Pridobi Stevilke Psalmov    "
echo -E " "
#
#  #Start_naslov#Psalm 1#Konec_naslov#
#
python3 pridobi_Stevilke_psalmov.py
#cat 19_PSA.usfm |grep -1 "človek, ki ne hodi po nasvetu"
echo -E " "
#cat 19_PSA.usfm |grep -1 "ko je bežal pred svojim"
#echo -E " "
#=============================================================


# ================= Pridobi Naslove Psalmov  ================================
echo -E "   --==    Pridobi Naslove Psalmov    "
echo -E " "
#
# In file 19_PSA.usfm
# are tags #Start_Psalm_title# and #End_Psalm_title#  and some_text between them.  #Start_Psalm_title# and #End_Psalm_title# are 
# some_text should be extracted from exact line and put two lines up, right after \c line.
# But if two lines up are \q1 line, then delete \q1 and instead insert \s1 and some_text
#
#  #Start_Psalm_title#Davidov psalm#End_Psalm_title# 
#       \s1
#
#
python3 pridobi_Naslove_psalmov.py
echo " "
#cat 19_PSA.usfm |grep -2 "pred svojim sinom Absalomom."
#echo -E " "
#cat 19_PSA.usfm |grep -1 "Pazljivo prisluhni mojim besedam"
#echo -E " "
echo -E "   --==    Odstrani naslove poglavij   "
#
#  Psalm 1   Psalm 2     sem drugače rešil, drugje pa se ne rabi.
#    Zato odstrani tage    #Start_naslov#  in  #Start_naslov#
python3 pridobi_odstrani_naslove.py
#cat 01_GEN.usfm |grep "#Start_naslov#"
#cat 67_REV.usfm |grep "#Start_naslov#"
#echo -E "--- "
#=============================================================


# ================= Pridobi Psalm 119 Alef  ================================
echo -E "   --==    Pridobi Psalm 119 Alef    "
echo -E " "
#
# In file 19_PSA.usfm
# are tags #Start_Psalm_title# and #End_Psalm_title#  and some_text between them.  #Start_Psalm_title# and #End_Psalm_title# are 
# some_text should be extracted from exact line and put two lines up, right after \c line.
# But if two lines up are \q1 line, then delete \q1 and instead insert \s1 and some_text
#
#  #Zacetek_Alef#\qa [ALEF א]#Konec_Alef#
#
# ====
# \c 119
# \q1
# \v 1  \p #Zacetek_Alef#\qa [ALEF א]#Konec_Alef#
# ====
# to 
# ========
# \c 119
# \qa [ALEF א]
# \q1
# \v 1  \p
# ========
sed -i '/\\c 119/{N;N;s/\(.*\)\n\(.*\)\n\(.*\) \\p #Zacetek_Alef#\\qa \[ALEF א\]#Konec_Alef#/\1\n\\qa \[ALEF א\]\n\2\n\3/}' 19_PSA.usfm
# cat 19_PSA.usfm  |grep  -2 "ALEF"
#
# \c 119
# \qa Aleph
# \q1
# \v 1  #Zacetek_Alef#\qa [ALEF א]#Konec_Alef#
#
python3 pridobi_Psalm_119_Alef.py
mv 19_PSA_modified.usfm 19_PSA.usfm
#cat 19_PSA.usfm |grep -2 "BET"
#echo -E "--- "
#cat 19_PSA.usfm |grep -2 "DALET"
#cat 19_PSA.usfm |grep "S čim naj mladenič"
echo -E " "
#=============================================================



      # ======= Kreira datoteko z dodatki - zemljevidi maps mapami =============
      #  https://ubsicap.github.io/usfm/peripherals/back.html
      touch A1_BAK.usfm
		echo "\id BAK"                 >> A1_BAK.usfm
		echo "\h Dodatki"              >> A1_BAK.usfm
		echo "\periph Kazalo zemljevidov|id=\"maps\""        >> A1_BAK.usfm
		echo "\toc1 Zemljevidi"        >> A1_BAK.usfm
		echo "\toc2 "                  >> A1_BAK.usfm
		echo "\toc3 "                  >> A1_BAK.usfm
		# echo "\mt Zemljevidi"          >> A1_BAK.usfm
		echo "\zfiga|p001\*"           >> A1_BAK.usfm
                echo "\pb"                     >> A1_BAK.usfm
		echo "\zfiga|p002\*"           >> A1_BAK.usfm
                echo "\pb"                     >> A1_BAK.usfm
		echo "\zfiga|p003\*"           >> A1_BAK.usfm
                echo "\pb"                     >> A1_BAK.usfm
		echo "\zfiga|p004\*"           >> A1_BAK.usfm
		echo "\zendperiph"             >> A1_BAK.usfm
                # cat A1_BAK.usfm
      # ========================================================================


# ======= Kreira strani   med Kazalom in SZ    in     med SZ in NZ  ============
      #   https://ubsicap.github.io/usfm/identification/books.html
      #   https://ubsicap.github.io/usfm/peripherals/index.html
      #   https://ubsicap.github.io/usfm/peripherals/intros.html
      case $format in
           "A4")
                touch A7_INT.usfm
		echo "\id INT"                                                     >> A7_INT.usfm
                echo "\periph Stara zaveza|id=\"intot\""                           >> A7_INT.usfm
                echo "\mt1 Stara zaveza"                                           >> A7_INT.usfm
                # echo "\p Stara zaveza je zapis......"                            >> A7_INT.usfm
	        echo "\pb"                                                         >> A7_INT.usfm
		echo "\zendperiph"                                                 >> A7_INT.usfm
                # echo "\periph History Introduction|id=\"inthistory\""            >> A7_INT.usfm
                # echo "\s1 Historical Books"                                      >> A7_INT.usfm
                # echo "\p The books in thi..."                                    >> A7_INT.usfm
		# echo "\zendperiph"                                               >> A7_INT.usfm
                # echo "\periph Poetry Introduction|id=\"intpoetry\""              >> A7_INT.usfm
                # echo "\s1 Books of Wisdom and Poetry"                            >> A7_INT.usfm
		# echo "\zendperiph"                                               >> A7_INT.usfm
                # echo "\periph Prophecy Introduction|id=\"intprophesy\""          >> A7_INT.usfm
                # echo "\s1 The Prophets"                                          >> A7_INT.usfm
		# echo "\zendperiph"                                               >> A7_INT.usfm
                # echo "\periph Deuterocanon Introduction|id=\"intdc\""            >> A7_INT.usfm
                # echo "\mt1 Deuterocanonicals/Apocrypha"                          >> A7_INT.usfm
                # echo "\p Most of the books g...."                                >> A7_INT.usfm
		# echo "\zendperiph"                                               >> A7_INT.usfm
                echo "\periph Nova zaveza|id=\"intnt\""                            >> A7_INT.usfm
                echo "\mt1 Nova zaveza"                                            >> A7_INT.usfm
                # echo "\p Knjige Noveze so napisali učenci Jezusa Kristusa....."  >> A7_INT.usfm
	        echo "\pb"                                                         >> A7_INT.usfm
		echo "\zendperiph"                                                 >> A7_INT.usfm
                # echo "\periph Gospels Introduction|id=\"intgospels\""            >> A7_INT.usfm
                # echo "\s1 Gospels and Acts"                                      >> A7_INT.usfm
		# echo "\zendperiph"                                               >> A7_INT.usfm
                # echo "\periph Epistles Introduction|id=\"intepistles\""          >> A7_INT.usfm
                # echo "\s1 The Letters of Paul"                                   >> A7_INT.usfm
		# echo "\zendperiph"                                               >> A7_INT.usfm
                # echo "\periph Letters Introduction|id=\"intletters\""            >> A7_INT.usfm
                # echo "\s1 General Letters and Revelation""                       >> A7_INT.usfm
		# echo "\zendperiph"                                               >> A7_INT.usfm
                # cat A7_INT.usfm
               ;;
           *)  #echo "   ."
               #echo "   Nic ne naredi."
                touch A7_INT.usfm
                echo "\id INT"                                                     >> A7_INT.usfm
                echo "\periph Stara zaveza|id=\"intot\""                           >> A7_INT.usfm
                #echo "\mt1 Stara zaveza"                                           >> A7_INT.usfm
                # echo "\p Stara zaveza je zapis......"                            >> A7_INT.usfm
                #echo "\pb"                                                         >> A7_INT.usfm
                echo "\zendperiph"                                                 >> A7_INT.usfm
                # echo "\periph History Introduction|id=\"inthistory\""            >> A7_INT.usfm
                # echo "\s1 Historical Books"                                      >> A7_INT.usfm
                # echo "\p The books in thi..."                                    >> A7_INT.usfm
                # echo "\zendperiph"                                               >> A7_INT.usfm
                # echo "\periph Poetry Introduction|id=\"intpoetry\""              >> A7_INT.usfm
                # echo "\s1 Books of Wisdom and Poetry"                            >> A7_INT.usfm
                # echo "\zendperiph"                                               >> A7_INT.usfm
                # echo "\periph Prophecy Introduction|id=\"intprophesy\""          >> A7_INT.usfm
                # echo "\s1 The Prophets"                                          >> A7_INT.usfm
                # echo "\zendperiph"                                               >> A7_INT.usfm
                # echo "\periph Deuterocanon Introduction|id=\"intdc\""            >> A7_INT.usfm
                # echo "\mt1 Deuterocanonicals/Apocrypha"                          >> A7_INT.usfm
                # echo "\p Most of the books g...."                                >> A7_INT.usfm
                # echo "\zendperiph"                                               >> A7_INT.usfm
                echo "\periph Nova zaveza|id=\"intnt\""                            >> A7_INT.usfm
                #echo "\mt1 Nova zaveza"                                            >> A7_INT.usfm
                # echo "\p Knjige Noveze so napisali učenci Jezusa Kristusa....."  >> A7_INT.usfm
                #echo "\pb"                                                         >> A7_INT.usfm
                echo "\zendperiph"                                                 >> A7_INT.usfm
                # echo "\periph Gospels Introduction|id=\"intgospels\""            >> A7_INT.usfm
                # echo "\s1 Gospels and Acts"                                      >> A7_INT.usfm
                # echo "\zendperiph"                                               >> A7_INT.usfm
                # echo "\periph Epistles Introduction|id=\"intepistles\""          >> A7_INT.usfm
                # echo "\s1 The Letters of Paul"                                   >> A7_INT.usfm
                # echo "\zendperiph"                                               >> A7_INT.usfm
                # echo "\periph Letters Introduction|id=\"intletters\""            >> A7_INT.usfm
                # echo "\s1 General Letters and Revelation""                       >> A7_INT.usfm
                # echo "\zendperiph"                                               >> A7_INT.usfm
                # cat A7_INT.usfm
               ;;
      esac
# =======================================================================================


      #============== Da ni v SLO-KJV med zemljevidi praznih strani ========================
      case $format in
           "SLO-KJV")


               echo -E "   --==    Pobrise \pb da ni med zemljevidi praznih strani"
               sed -i "s|\\\\pb||g"             A1_BAK.usfm
               ;;
           *)  echo -E "   --==    Nic ne naredi. Obicajno Sveto pismo  (ni SLO-KJV) ... "
               ;;
      esac
      #cat A1_BAK.usfm
      #=============================================================================================

#======================================================================================
echo -E "   --==    Popravi znak \p eno vrstico visje v vseh usfm datotekah"
#                    > \p   
#    \v 6 \p Text    > \v 6 Text
sed -i "s/^\\\\v \([0-9]*\) \\\\p /\x5cp\n\x5cv \1 /g"  *.usfm 
#
#   Za Uvodom se pri vrstici 1 začne . Če tega ne narediš je prva vrstica pri uvodu
#   Za \c 1     doda enter   
sed -i "s/^\\\\c \([0-9]*\)/\x5cc \1\n\x5cp/g"          *.usfm
# 
# Pri Psalmih potem pobriše vse \p vrstice   xxxx
sed -i "/^\\\\p/d"                                      19_PSA.usfm
# cat 19_PSA.usfm |grep "\p "
# =======================================================


# ======= Doda \p vrstico povsod kjer je \v 1 ===========
# Potem doda \p vrstico povsod kjer je \v 1  
#  
# \c 3                    \c3
# \s Davidov psalm    ->  \s Davidov psalm      (ta vrstica je ali pa ni)
# \v 1                    \p
#                         \v 1
#
# cat 19_PSA.usfm |grep -1  "je bežal pred svojim sinom Absalomom"
echo " "
sed -i '/^\\v 1 /{x;p;x;s/^\\v 1 /\\p\n\\v 1 /;}'       19_PSA.usfm
# Tole zgoraj Naredi nekaj praznih vrstic  v 19_PSA.usfm
#cat 19_PSA.usfm |grep -1 "\p "
# cat 19_PSA.usfm |grep  -1 "je bežal pred svojim sinom Absalomom"
# ========================================================


# ================= Odstrani prazne vrstice =================================
echo -E "   --==    Odstrani prazne vrstice v Ps 119   "
echo -E " "
sed -i -e "/^$/d"                                       19_PSA.usfm
# ============================================================================


# ================= Pridobi BET \n \p  ================================
echo -E "   --==    Pridobi BET \n \p    "
echo -E " "
#
# Tukaj še ne deluje 
# Do a Python script. 
# Find lines in 19_PSA.usfm started with "\qa"
# After that line make  a line with "\p"
# But if you find line "\qa [ALEF א]" do not do a line with "\p"
# Changes save in the same file

#  Za vsako hebrejsko ško naredi prazno vrstico, razen pri ALEF, kjer je že
python3 pridobi_Psalm_119_Bet_p.py
# cat 19_PSA.usfm |grep -1 "Absalom"
echo -E " "
#cat 19_PSA.usfm |grep -1 "ko je bežal pred svojim"
#echo -E " "
#=============================================================


# ================= SELAH ================================
echo -E "   --==    SELAH    "
#    To sem odstranil ne vem več zakaj....       </verse><lg><l type=\"selah\"> Sela.</l></lg>    "
#    Pridela se lahko nazaj, ker je to samo v knjigi Ps in Hab.
#              \qs  \qs*
echo -E " "
sed -i "s| Sela.|\\\qs Sela. \\\qs*|g" 19_PSA.usfm
sed -i "s| Sela.|\\\qs Sela. \\\qs*|g" 35_HAB.usfm

cat SloKJV_sword.xml |grep "\qs"
cat SloKJV_sword.xml |grep -F 'type="selah">'
#=============================================================


#========== Rdece Jezusove besede =========================
#  Pri barvnem tisku popravi nazaj na wj   in   wj*
#echo -E "   --==    Rdece JEZUSOVE BESEDE ==--"
#echo -E "   --==       Words of Jesus begin  <q who=\"Jesus\" marker=\"\">  \</q>    "
#echo -E "   --==       \wj     \wj*    "    
#echo -E "   --==    CB tisk moba biti \bd in \bd*  "    
# Zamenja #rz#  ->
#sed -i "s/\\\\wj /\\\\bd /g"     *.usfm
#sed -i "s/\\\\wj* /\\\\bd* /g"   *.usfm
#==========================================================


# =========================================================
# Dva presledka zamenja z enim presledkom
sed -i "s/  / /g"                   *.usfm
# cat 44_JHN.usfm |grep "lovek, poslan od Boga"
#==========================================================


#============== Odstrani UVOD iz naslednjih knjig ========================
      case $format in
           "A5_NZ_BIG")
               echo -E "   --==    Ker je A5_NZ_BIG -> Pobrise uvod - celo vrstico ki se zacne z \ip"
               sed -i '/^\\imt1/d'  *.usfm
               sed -i '/^\\ip/d'    *.usfm
               ;;
           *)  echo -E "   --==    Nic ne naredi. Obicajno Sveto pismo (ni A5_NZ_BIG)... "
               ;;
      esac
      # head 66_JUD.usfm
#=============================================================================================


echo -E "   --==    Pozene izdelavo PDF datoteke ==--"
echo -E "   --==    Popravi naslove knjig ==--"

# \h 1 Pet
# \h1 Prvo Petrovo pismo       - to potegne iz SloKJV_sword.sml datoteke
# \toc1 Prvo Petrovo pismo     - to potegne iz SloKJV_sword.sml datoteke
# \toc2 1 Peter
# \toc3 1 Pet
# \mt1 Prvo Petrovo pismo      - to potegne iz SloKJV_sword.sml datoteke


# GEN
  sed -i "s/\\\\h /\x5ch 1 Mz/g"                 01_GEN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Geneza/g"          01_GEN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Mz/g"             01_GEN.usfm

# EXO
  sed -i "s/\\\\h /\x5ch 2 Mz/g"                 02_EXO.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Eksodus/g"         02_EXO.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Mz/g"             02_EXO.usfm

# LEV
  sed -i "s/\\\\h /\x5ch 3 Mz/g"                 03_LEV.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Levitik/g"         03_LEV.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 3Mz/g"             03_LEV.usfm

# NUM
  sed -i "s/\\\\h /\x5ch 4 Mz/g"                 04_NUM.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Numeri/g"          04_NUM.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 4Mz/g"             04_NUM.usfm

# DEU
  sed -i "s/\\\\h /\x5ch 5 Mz/g"                 05_DEU.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Devteronomij/g"    05_DEU.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 5Mz/g"             05_DEU.usfm

# JOS
#  UTF-8   U+00F3  ó   c3 b3  \xC3\xB3
  sed -i "s/\\\\h /\x5ch Joz/g"                  06_JOS.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 J\xC3\xB3zue/g"    06_JOS.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Joz/g"             06_JOS.usfm

# JDG
  sed -i "s/\\\\h /\x5ch Sod/g"                  07_JDG.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Sodniki/g"         07_JDG.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Sod/g"             07_JDG.usfm

# RUT
  sed -i "s/\\\\h /\x5ch Ruta/g"                 08_RUT.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Ruta/g"            08_RUT.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Rut/g"             08_RUT.usfm

# 1SA
  sed -i "s/\\\\h /\x5ch 1 Sam/g"                09_1SA.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Samuel/g"        09_1SA.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Sa/g"             09_1SA.usfm

# 2SA
  sed -i "s/\\\\h /\x5ch 2 Sam/g"                10_2SA.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Samuel/g"        10_2SA.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Sa/g"             10_2SA.usfm

# 1KI
  sed -i "s/\\\\h /\x5ch 1 Kr/g"                 11_1KI.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Kralji/g"        11_1KI.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Kr/g"             11_1KI.usfm

# 2KI
  sed -i "s/\\\\h /\x5ch 2 Kr/g"                 12_2KI.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Kralji/g"        12_2KI.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Kr/g"             12_2KI.usfm

# 1CH
  sed -i "s/\\\\h /\x5ch 1 Krn/g"                13_1CH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Kroniška/g"      13_1CH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Krn/g"            13_1CH.usfm

# 2CH
  sed -i "s/\\\\h /\x5ch 2 Krn/g"                14_2CH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Kroniška/g"      14_2CH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Krn/g"            14_2CH.usfm

# EZR
  sed -i "s/\\\\h /\x5ch Ezra/g"                 15_EZR.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Ezra/g"            15_EZR.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Ezr/g"             15_EZR.usfm

# NEH
  sed -i "s/\\\\h /\x5ch Neh/g"                  16_NEH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Nehemija/g"        16_NEH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Neh/g"             16_NEH.usfm

# EST
  sed -i "s/\\\\h /\x5ch Est/g"                  17_EST.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Estera/g"          17_EST.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Est/g"             17_EST.usfm

# JOB
  sed -i "s/\\\\h /\x5ch Job/g"                  18_JOB.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Job/g"             18_JOB.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Job/g"             18_JOB.usfm

# PSA
  sed -i "s/\\\\h /\x5ch Ps/g"                   19_PSA.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Psalmi/g"          19_PSA.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Ps/g"              19_PSA.usfm

# PRO
  sed -i "s/\\\\h /\x5ch Prg/g"                  20_PRO.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Pregovori/g"       20_PRO.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Prg/g"             20_PRO.usfm

# ECC
  sed -i "s/\\\\h /\x5ch Prd/g"                  21_ECC.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Pridigar/g"        21_ECC.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Prd/g"             21_ECC.usfm

# SNG
  sed -i "s/\\\\h /\x5ch Pp/g"                   22_SNG.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Pesem pesmi/g"     22_SNG.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Pp/g"              22_SNG.usfm

# ISA
  sed -i "s/\\\\h /\x5ch Iz/g"                   23_ISA.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Izaija/g"          23_ISA.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Iz/g"              23_ISA.usfm

# JER
  sed -i "s/\\\\h /\x5ch Jer/g"                  24_JER.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Jeremija/g"        24_JER.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jer/g"             24_JER.usfm

# LAM
  sed -i "s/\\\\h /\x5ch Žal/g"                  25_LAM.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Žalostinke/g"      25_LAM.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Žal/g"             25_LAM.usfm

# EZK
  sed -i "s/\\\\h /\x5ch Ezk/g"                  26_EZK.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Ezekiel/g"         26_EZK.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Ezk/g"             26_EZK.usfm

# DAN
  sed -i "s/\\\\h /\x5ch Dan/g"                  27_DAN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Daniel/g"          27_DAN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Dan/g"             27_DAN.usfm

# HOS
  sed -i "s/\\\\h /\x5ch Oz/g"                   28_HOS.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Ozej/g"            28_HOS.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Oz/g"              28_HOS.usfm

# JOL
  sed -i "s/\\\\h /\x5ch Jl/g"                   29_JOL.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Joel/g"            29_JOL.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jl/g"              29_JOL.usfm

# AMO
  sed -i "s/\\\\h /\x5ch Am/g"                   30_AMO.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Amos/g"            30_AMO.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Am/g"              30_AMO.usfm

# OBA
  sed -i "s/\\\\h /\x5ch Abd/g"                  31_OBA.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Abdija/g"          31_OBA.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Abd/g"             31_OBA.usfm

# JON
  sed -i "s/\\\\h /\x5ch Jon/g"                  32_JON.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Jona/g"            32_JON.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jon/g"             32_JON.usfm

# MIC
  sed -i "s/\\\\h /\x5ch Mih/g"                  33_MIC.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Mihej/g"           33_MIC.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Mih/g"             33_MIC.usfm

# NAM
  sed -i "s/\\\\h /\x5ch Nah/g"                  34_NAM.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Nahum/g"           34_NAM.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Nah/g"             34_NAM.usfm

# HAB
  sed -i "s/\\\\h /\x5ch Hab/g"                  35_HAB.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Habakuk/g"         35_HAB.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Hab/g"             35_HAB.usfm

# ZEP
  sed -i "s/\\\\h /\x5ch Sof/g"                  36_ZEP.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Sofonija/g"        36_ZEP.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Sof/g"             36_ZEP.usfm

# HAG
  sed -i "s/\\\\h /\x5ch Ag/g"                   37_HAG.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Agej/g"            37_HAG.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Ag/g"              37_HAG.usfm

# ZEC
  sed -i "s/\\\\h /\x5ch Zah/g"                  38_ZEC.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Zaharija/g"        38_ZEC.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Zah/g"             38_ZEC.usfm

# MAL
  sed -i "s/\\\\h /\x5ch Mal/g"                  39_MAL.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Malahija/g"        39_MAL.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Mal/g"             39_MAL.usfm

# MAT
  sed -i "s/\\\\h /\x5ch Mt/g"                   41_MAT.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Matej/g"           41_MAT.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Mt/g"              41_MAT.usfm

# MRK
  sed -i "s/\\\\h /\x5ch Mr/g"                   42_MRK.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Marko/g"           42_MRK.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Mr/g"              42_MRK.usfm

# LUK
  sed -i "s/\\\\h /\x5ch Lk/g"                   43_LUK.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Luka/g"            43_LUK.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Lk/g"              43_LUK.usfm

# JHN
  sed -i "s/\\\\h /\x5ch Jn/g"                   44_JHN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Janez/g"           44_JHN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jn/g"              44_JHN.usfm

# ACT
  sed -i "s/\\\\h /\x5ch Apd/g"                  45_ACT.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Apostolska dela/g" 45_ACT.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Apd/g"             45_ACT.usfm

# ROM
  sed -i "s/\\\\h /\x5ch Rim/g"                  46_ROM.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Rimljanom/g"       46_ROM.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Rim/g"             46_ROM.usfm

# 1CO
  sed -i "s/\\\\h /\x5ch 1 Kor/g"                47_1CO.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Korinčanom/g"    47_1CO.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Ko/g"             47_1CO.usfm

# 2CO
  sed -i "s/\\\\h /\x5ch 2 Kor/g"                48_2CO.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Korinčanom/g"    48_2CO.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Ko/g"             48_2CO.usfm

# GAL
  sed -i "s/\\\\h /\x5ch Gal/g"                  49_GAL.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Galačanom/g"       49_GAL.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Gal/g"             49_GAL.usfm

# EPH
  sed -i "s/\\\\h /\x5ch Ef/g"                   50_EPH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Efežanom/g"        50_EPH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Ef/g"              50_EPH.usfm

# PHP
  sed -i "s/\\\\h /\x5ch Flp/g"                  51_PHP.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Filipljanom/g"     51_PHP.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Flp/g"             51_PHP.usfm

# COL
  sed -i "s/\\\\h /\x5ch Kol/g"                  52_COL.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Kološanom/g"       52_COL.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Kol/g"             52_COL.usfm

# 1TH
  sed -i "s/\\\\h /\x5ch 1 Tes/g"                53_1TH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Tesaloničanom/g" 53_1TH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Te/g"             53_1TH.usfm

# 2TH
  sed -i "s/\\\\h /\x5ch 2 Tes/g"                54_2TH.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Tesaloničanom/g" 54_2TH.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Te/g"             54_2TH.usfm

# 1TI
  sed -i "s/\\\\h /\x5ch 1 Tim/g"                55_1TI.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Timóteju/g"      55_1TI.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Ti/g"             55_1TI.usfm

# 2TI
  sed -i "s/\\\\h /\x5ch 2 Tim/g"                56_2TI.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Timóteju/g"      56_2TI.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Ti/g"             56_2TI.usfm

# TIT
  sed -i "s/\\\\h /\x5ch Tit/g"                  57_TIT.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Titu/g"            57_TIT.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Tit/g"             57_TIT.usfm

# PHM
  sed -i "s/\\\\h /\x5ch Fil/g"                  58_PHM.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Filemonu/g"        58_PHM.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Fil/g"             58_PHM.usfm

# HEB
  sed -i "s/\\\\h /\x5ch Heb/g"                  59_HEB.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Hebrejcem/g"       59_HEB.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Heb/g"             59_HEB.usfm

# JAS
  sed -i "s/\\\\h /\x5ch Jak/g"                  60_JAS.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Jakob/g"           60_JAS.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jak/g"             60_JAS.usfm

# 1PE
  sed -i "s/\\\\h /\x5ch 1 Pet/g"                61_1PE.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Peter/g"         61_1PE.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Pt/g"             61_1PE.usfm

# 2PE
  sed -i "s/\\\\h /\x5ch 2 Pet/g"                62_2PE.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Peter/g"         62_2PE.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Pt/g"             62_2PE.usfm

# 1JN
  sed -i "s/\\\\h /\x5ch 1 Jn/g"                 63_1JN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 1 Janez/g"         63_1JN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 1Jn/g"             63_1JN.usfm

# 2JN
  sed -i "s/\\\\h /\x5ch 2 Jn/g"                 64_2JN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 2 Janez/g"         64_2JN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 2Jn/g"             64_2JN.usfm

# 3JN
  sed -i "s/\\\\h /\x5ch 3 Jn/g"                 65_3JN.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 3 Janez/g"         65_3JN.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 3Jn/g"             65_3JN.usfm

# JUD
  sed -i "s/\\\\h /\x5ch Jud/g"                  66_JUD.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Juda/g"            66_JUD.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Jud/g"             66_JUD.usfm

# REV
  sed -i "s/\\\\h /\x5ch Raz/g"                  67_REV.usfm
  sed -i "s/\\\\toc2/\x5ctoc2 Razodetje/g"       67_REV.usfm
  sed -i "s/\\\\toc3/\x5ctoc3 Raz/g"             67_REV.usfm



	# C:\Program Files\PTXprint\PTXprint.exe" -c Diglot XYZ
	# will OPEN PTXprint with XYZ project active and the saved configuration called "Diglot" (but won't print anything)
	#
	# "C:\Program Files\PTXprint\PTXprint.exe" -c NTandPsalms -P XYZ
	# will directly create/PRINT a PDF from the XYJ project using the saved configuration called "NTandPsalms" (no GUI will appear)
	#
	# "C:\Program Files\PTXprint\PTXprint.exe" -b ROM -c SideXrefs -P XYZ
	# will directly create a PDF of the BOOK of ROMANS from the XYJ project using the saved configuration called "SideXrefs" (no GUI will appear)
	#
	# "C:\Program Files\PTXprint\PTXprint.exe" -b "MAT MRK LUK JHN ACT GLO" -P XYZ
	# will directly create a PDF of 4 gospels, Acts and Glossary from the XYJ project using the Default configuration (no GUI will appear)
	#
	# "C:\Program Files\PTXprint\PTXprint.exe" -d "C:\Temp"
	# runs PTXprint, and output PDF files will be created in C:\Temp folder instead of C:\My Paratext 9 Projects\<XYZ>\local\ptxprint
	#
	# From your example, it looks like you are trying to load a particular project from a specific location, and using -p to provide the Path to Paratext Projects directory. Note that this needs to point to the PARENT path of one or more Paratext/USFM project folders. So, for example, on a Windows system, -p is usually pointing to "C:\My Paratext 9 Projects" under which there are several PROJECT folders (in which the USFM files reside).
	#
	# So perhaps what you need to enter is:
	#
	# ptxprint -p /home/pc/Dokumenti/osos2usfm/SloKJV/release/ XYZ 
	#
	# where XYZ is replaced by the Project Name/Code.


#============= Doda STARA ZAVEZA in NOVA ZAVEZA  ==============
      case $format in
           "A4")
               #echo -E "   --==    Nic ne naredi"
               ;;
           *)  #echo -E "   --==    Doda STARA ZAVEZA in NOVA ZAVEZA  in page break med Staro in Novo zavezo  ==--"
               # Gleda na string   \mt1 Prva Mojzesova knjiga
               #sed -i "s|\(\\\mt1 Prva Mojzesova knjiga\)|\\\pb\n\\\mt1 STARA ZAVEZA\n\\\pb\n\\\pb\n\1|g"           01_GEN.usfm
               # Gleda na string   \toc3 Mt
               ;;
      esac
#============================================================================================
# xxx nisem pregledal
#  Ce je Samo nova zaveza mora biti med kazalom in Mt 1 stran frej da se Mt zacne na desni strani
     case $format in
          "A5_NZ")
              #echo " "
              #echo -E "   --==    Samo Nova zaveza ..."
              #echo "              med kazalom in Mt 1 stran frej da se Mt zacne na desni strani "
              #echo " "
              #sed -i "s|\(\\\toc3 Mt\)|\1\n\\\mt1 NOVA ZAVEZA\n\\\pb\n|g"         41_MAT.usfm
              ;;
          *)  #echo -E "   --==    Celotno Sveto pismoo ... "
              #sed -i "s|\(\\\toc3 Mt\)|\1\\n\\\mt1 NOVA ZAVEZA\n\\\pb\n|g"        41_MAT.usfm
              ;;
     esac
#=============================================================================================


#========== Doda QR kodo ===============
sed -i "s/Lepa zaradi lege/Lepa zaradi lege \\\zqrcode|pgpos=\"cr\" size=\"1.7cm\" data=\"https:\/\/www.brighteon.com\/fc8a3ecf-7b86-469e-b7fb-ea723c84e347\"\\\* /g"                                      19_PSA.usfm
#cat 19_PSA.usfm |grep -2 "Lepa zaradi lege"
sed -i "s/da se mazili Najsvetejše./da se mazili Najsvetejše. \\\zqrcode|pgpos=\"cr\" size=\"1.6cm\" data=\"https:\/\/github.com\/msavli\/Ronald_Wyatt\"\\\* /g"                                           27_DAN.usfm
# cat 27_DAN.usfm |grep -1 "da se mazili Najsvetejše."
sed -i "s/›Jaz sem Kralj Judov.‹«/›Jaz sem Kralj Judov.‹« \\\zqrcode|pgpos=\"cr\" size=\"1.9cm\" data=\"https:\/\/relojprofetico.blogspot.com\/2010\/07\/yeshua-hanotzri-wmelej-hayehudim.html\"\\\* /g"   44_JHN.usfm
#cat 44_JHN.usfm |grep -1 "›Jaz sem Kralj Judov.‹«"
#========================================


# Počisti za samo ime Biblije ki jo je izvozil iz XML datoteke.
rm 00_BibleName.txt


# ======== Prestavi usfm datotke v pravo mapo za PTXPRINT" =============================
echo -E "   --==    Prestavi usfm datotke v pravo mapo za PTXPRINT"
mv $osis2usfm/*.usfm $SloKJV$format/ >/dev/null 2>&1
echo -E " " 
echo -E "   ======= Koncal generiranje usfm datotek ========= "
echo -E " " 
	# ls -al 
# ======================================================================================


#=================  PTXPRINT  ============================
echo -E "   --==    PTXPRINT                           "
echo -E " "
echo -E "   ptxprint -p $osis2usfm/SloKJV/release -c Default SloKJV_$format"
echo -E " "
echo -E " "
#                    -p  the path to the BASE of where one or more "Paratext Projects" are stored
#                    -c the config name (currently just 'Default' - but you can use Save As... to make a different config name once the UI opens up)
#                    And then finally (without any parameter) the Project name 'SloKJV_A4'
#                    You can always use ptxprint -h to explain all the parameters.
# cd /home/pc/Dokumenti/osis2usfm/SloKJV/release
# ptxprint SloKJV_$format
# cd /home/pc/Dokumenti/osis2usfm
# ptxprint -c  /home/pc/Dokumenti/osis2usfm/SloKJV/release SloKJV_$format
ptxprint -p $osis2usfm/SloKJV/release -c Default SloKJV_$format
#====================================================


#===========  Spredaj doda 6 A4 strani SloKJV PDF-ju  =======================================
#              to je ze v PTXprint nastavljeno
#echo -E "   --==    Zadaj doda zemljevide SloKJV PDF-ju ==--"
#echo "   pdfunite $osis2usfm/uvod/SloKJV_"$format"_prvi_del_knjige.pdf $SloKJV$format/local/ptxprint/SloKJV_"$format"_Default_GEN-REV_ptxp.pdf $SloKJV_Github/SloKJV_"$format"_dva_stolpca.pdf"
#echo  "   Kopira v Github mapo ..."
#============================================================================================
#  Ce je Samo nova zaveza se fajl drugace imenuje    ...PSA-REV_ptxp.pdf
     case $format in
          "A5_NZ")
              echo " "
              echo "   Samo Nova zaveza ..."
              echo " "
              cp $SloKJV$format/local/ptxprint/SloKJV_"$format"_Default_PSA-BAK_ptxp_CMYK.pdf $SloKJV_Github/SloKJV_"$format"_dva_stolpca.pdf
              ;;
          *)  echo "  Celotno Sveto pismo ... "
              cp $SloKJV$format/local/ptxprint/SloKJV_"$format"_Default_GEN-BAK_ptxp_CMYK.pdf $SloKJV_Github/SloKJV_"$format"_dva_stolpca.pdf
              ;;
     esac
#=============================================================================================

#============ Pozene GITHUB Desktop? ========================
echo " "
echo "   Pozene GITHUB Desktop?"
echo " "
PS5='   Izberi: '
options_ver=("Ne" "Pozene" "Izhod")
select opt_ver in "${options_ver[@]}"
do
      case $opt_ver in
          "Ne")
              echo " "
              echo "    Pa drugic sinhronizacija z Githubom."
              echo " "
              break
             ;;
          "Pozene")
              echo " "
              echo "   Izbral si nadgraditev."
              echo " "
              echo "     Sinhronizacija z Githubom ..."
              echo " "
              echo "   --==  Pozene /usr/bin/github-desktop ==--"
                #================================================================================
                echo -E "  Ocisti mape zacasnih datotek..."
                find $SloKJV_Github/PTXprint/osis2usfm/SloKJV/release/SloKJV_$format -name '*.usfm'     -exec rm {} \;        >/dev/null 2>&1
                find $SloKJV_Github/PTXprint/osis2usfm/SloKJV/release/SloKJV_$format -name '*.usfm.adj' -exec rm {} \;        >/dev/null 2>&1
                find $SloKJV_Github/PTXprint/osis2usfm/SloKJV/release/SloKJV_$format -name 'local'      -exec rm -rf {} \;    >/dev/null 2>&1
                #================================================================================
              /usr/bin/github-desktop
              break
              ;;
          "Izhod")
              echo " "
              echo "   Izbral si $REPLY kar je $opt_ver"
              echo " "
              exit
             ;;
          *) echo "Napacna izbira $REPLY";;
     esac
done
#====================================================
