#!/bin/bash

# Set paths
SloKJVepubPath=/home/pc/Dokumenti/epub
# Od tukaj pobira Python skripta
SloKJV_Module_Path=/home/pc/.sword
SloKJV_Mods_Path=/home/pc/.sword/mods.d
# Sem daje Sword Glej navodila... https://wiki.crosswire.org/Tutorial:Compiling_%26_Installing_SWORD
# SloKJV_Module_Path=/usr/share/sword/modules/texts/ztext/slokjv
# SloKJV_Mods_Path=/usr/share/sword/mods.d
SloKJV_Github=/home/pc/Dokumenti/GitHub/SloKJV

# SloKJV module from Github
# wget https://github.com/msavli/SloKJV/raw/master/SloKJV_sword.xml -O $SloKJVepubPath/SloKJV_sword.xml
#   To sem dobil iz   git clone https://github.com/pierre-amadio/SwordSandBox

echo
echo "   Vlecem iz Githuba....  zakomentirano"
echo 
cd $SloKJV_Github
git pull


# Create folders
mkdir  $SloKJVepubPath                                                         >/dev/null 2>&1
cd $SloKJVepubPath
rm -rf html
mkdir html                                                                      >/dev/null 2>&1
mkdir $SloKJV_Module_Path                                                       >/dev/null 2>&1
mkdir $SloKJV_Module_Path/modules                                               >/dev/null 2>&1
mkdir $SloKJV_Module_Path/modules/texts                                         >/dev/null 2>&1
mkdir $SloKJV_Module_Path/modules/texts/ztext                                   >/dev/null 2>&1
mkdir $SloKJV_Module_Path/modules/texts/ztext/slokjv                            >/dev/null 2>&1

# Kopira predloge in kaj je se za narediti
cp templates/foreword.html          html/02-Foreword.html
cp templates/cover.html             html/00_preimenuj_me_v_cover.xhtml
cp templates/content_opf.xhtml      html/00_vsebino_metadata_daj_v_content.opf_in_popravi_datum_.xhtml
echo "<html><body></body></html>" > html/00_pobrisi_Section001.xhtml
echo "<html><body></body></html>" > html/00_dodaj_font.xhtml
echo "<html><body></body></html>" > html/00_vsebino_toc.ncx_prekopiraj_v_toc.ncx_fajl.xhtml


echo
echo "        Prekopiram conf datoteko SloKJV modula "
cp $SloKJV_Github/slokjv.conf $SloKJV_Mods_Path/slokjv.conf
echo
echo "   Kreiram SloKJV modul iz SloKJV_sword.xml datoteke ..."
osis2mod $SloKJV_Module_Path/modules/texts/ztext/slokjv $SloKJV_Github/SloKJV_sword.xml -v KJVA -z
# osis2mod /usr/share/sword/modules/texts/ztext/slokjv/ /home/pc/Dokumenti/GitHub/SloKJV/SloKJV_sword.xml -v KJVA -z

# Patch from
# wget https://parlons-de-dragons.com/slokjv/slokjv.diff --no-check-certificate -O $SloKJVepubPath/slokjv.diff
# patch $SloKJVepubPath/test.py slokjv.diff 

# Making html files...
#  Sword datoteko vzame iz mape /home/pc/.sword
#  Naslove knjig Razodetje,..  vzame iz /home/pc/Dokumenti/epub/templates/sl-utf8.conf
echo
echo "   Kreiram html datoteke..."
echo
python3 $SloKJVepubPath/test.py   # |& tee    log.txt


cd html


echo
echo "   Preimenujem datoteke poglavij da bodo imele  *-1.html  ->  *-0001.htm  *-0002.htm ..."
# Loop through all HTML files in the current directory
for file in *.html; do
  # Extract the base name and the extension
  base="${file%.html}"

  # Use regex to separate the parts of the filename
  if [[ $base =~ ([0-9][0-9]-[0-9A-Za-z]+-)([0-9]+) ]]; then
    prefix="${BASH_REMATCH[1]}"
    number="${BASH_REMATCH[2]}"

    # Pad the number with leading zeros to make it 3 digits
    new_number=$(printf "%04d" "$number")

    # Construct the new filename
    new_file="${prefix}${new_number}.html"

    # Rename the file
    mv "$file" "$new_file"
  fi
done


echo "   Preimenujem datoteke knjig da bodo imele   68-Rev.html  ->  68-Rev-0000.htm"
# Loop through all HTML files in the current directory
for file in *.html; do
  # Extract the base name and the extension
  base="${file%.html}"

  # Use regex to separate the parts of the filename
  if [[ $base =~ ([0-9][0-9]-[0-9A-Z][A-Za-z]+) ]]; then
    prefix="${BASH_REMATCH[1]}"

    # Construct the new filename
    new_file="${prefix}-0000.html"

    # Rename the file
    mv "${prefix}.html" "$new_file" /dev/null 2>/dev/null 
  fi
done


echo "   Zdruzi knjige in poglavja od pripadajocih knjig  ->  68-Rev.html "
# Define the prefix pattern
prefix_pattern='^[0-9]{2}-[A-Z0-9][A-Za-z]+-'

# Get the list of files in the current directory
files=$(ls)

# Iterate over each file
for file in $files; do
    # Check if the file name matches the prefix pattern
    if [[ $file =~ $prefix_pattern ]]; then
        # Extract the prefix
        prefix=${BASH_REMATCH[0]}
        # Find all files with the same prefix
        matching_files=$(ls ${prefix}*.html)
        # Concatenate the contents of the matching files into a new file
        cat $matching_files > "${prefix::-1}.html"
    fi
done


echo "   Pobrisem datoteke od knjig in od poglavij"
# Define the pattern
   pattern='^[0-9][0-9]-[A-Z0-9][A-Za-z]+-[0-9]+\.html$'
   # Use find to locate and delete files matching the pattern
   find . -type f -regex './[0-9][0-9]-[A-Z0-9][A-Za-z]+-[0-9][0-9][0-9][0-9]\.html' -exec rm {} \;
echo "   Files deleted successfully."
echo



# Define the header content
header='<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<head>
<title></title>
<link rel="stylesheet" type="text/css" href="../Styles/style.css"/>
</head>
<body>'


# Define the footer content
footer='</body>
</html>'

# Loop through files matching the pattern
for file in [0-9][0-9]-[A-Z0-9][A-Za-z]*.html; do
    # Create a temporary file
    tmpfile=$(mktemp)
    # Add the header to the temporary file
    echo "$header" > "$tmpfile"
    # Append the footer to the file
    echo "$footer" >> "$file"
    # Append the original file content to the temporary file
    cat "$file" >> "$tmpfile"
    # Move the temporary file to the original file
    mv "$tmpfile" "$file"
done


echo
echo "   Popravljam html datoteke..."
echo
# Paragraphs replaced line before with <p>\&nbsp;<\/p>
#sed -i ':a;N;$!ba;s/\(<span class=\"verseNbr\">[0-9]\+<\/span>\)\n   \n/<p>\&#160;<\/p>\n  \1\n   /g'  $SloKJVepubPath/html/*.html
sed -i ':a;N;$!ba;s/\(<span class=\"verseNbr\">[0-9]\+<\/span>\)\n   \n/<br \/>\n  \1\n   /g'  $SloKJVepubPath/html/*.html

# Hebrejske crke - dodam prelom, da gr besedilo v novo vrstico    [iz]<br>  pa potem nazaj popravim
sed -i 's/]/]<br \/>/g'       $SloKJVepubPath/html/21-Ps.html     ### 21-Ps-119.html
sed -i 's/iz\]<br \/>/iz\]/g' $SloKJVepubPath/html/21-Ps.html     ### 21-Ps-119.html

# Pred hebrejskimi crkami nardi <br>
# yet to do


# Popravi kazalo da ni pikice pred -Kazalo in ga spremeni v H2
#  13 <li>
#  14  <a href="01-toc.html">Kazalo</a>
#  15  </li>
sed -i ':a;N;$!ba;s/<ul>\n<li>\n <a href=\"01-toc.html\">Kazalo knjig<\/a>\n <\/li>/<H2>Kazalo knjig<\/H2>\n<ul>/g' $SloKJVepubPath/html/01-toc.html

# Spravi gor <ul> za dve vrstici
#</a>
# 
# <ul>
sed -i ':a;N;$!ba;s/<\/a>\n \n <ul>/<\/a><ul>/g' $SloKJVepubPath/html/01-toc.html

echo "    #Spravi gor <li> za eno vrstico in vmes doda presledek"
sed -i ':a;N;$!ba;s/<li>\n <a/<li> <a/g' $SloKJVepubPath/html/01-toc.html

echo "   Pri vrstici Pregovor odstrani prvi presledek v tej vrstici "
echo "      da ne pride to dvakrat v kazalo "
echo "      in baskslah li da eno visje "
sed -i ':a;N;$!ba;s/<li> <a href=\"02-foreword.html\">Predgovor<\/a>\n <\/li>/<li><a href=\"02-foreword.html\">Kolofon in predgovor<\/a><\/li><br \/>/g' $SloKJVepubPath/html/01-toc.html

rm $SloKJVepubPath/templates/toc_temp.txt     >/dev/null 2>&1
echo "   Doda dodatno kazalo knjig v zacasno datoteko in uposteva dodan presledek dve vrstici nazaj"
cat $SloKJVepubPath/html/01-toc.html |grep '<li> <a' >$SloKJVepubPath/templates/toc_temp.txt

echo "   Zamenja ul z  baskslash li"
sed -i 's/<ul>/<\/li>/g' $SloKJVepubPath/templates/toc_temp.txt

echo '<h2>Podrobno kazalo</h2>' >> $SloKJVepubPath/templates/toc_temp.txt

# awk  -vn=1 '{print}; /Predgovor/ && n{while (getline <"templates/toc_temp.txt") print;n=0}' html/01-toc.html >html/01-toc-popravljen.html 
awk   -v n=1 '{print}; /Predgovor/ && n{while (getline <\"templates/toc_temp.txt\") print;n=0}' html/01-toc.html > html/01-toc-popravljen.html

mv html/01-toc-popravljen.html html/01-toc.html

# Pobrise zacasno datoteko
rm templates/toc_temp.txt

# Obe Kroniske dobita sumnik in kazalo
#sed -i 's/Kroniska/Kroniška/g' $SloKJVepubPath/html/01-toc.html
#sed -i 's/Kroniska/Kroniška/g' $SloKJVepubPath/html/15-1Chr*.html
#sed -i 's/Kroniska/Kroniška/g' $SloKJVepubPath/html/16-2Chr*.html

# Visoka pesem rata Pesem pesmi
#sed -i 's/Visoka pesem/Pesem pesmi/g' $SloKJVepubPath/html/01-toc.html

# Zalostinke dobi ZZ
#sed -i 's/Zalostinke/Žalostinke/g' $SloKJVepubPath/html/01-toc.html
#sed -i 's/Zalostinke/Žalostinke/g' $SloKJVepubPath/html/27-Lam*.html

# Dela postane Apostoslska dela
#sed -i 's/Dela/Apostolska dela/g' $SloKJVepubPath/html/01-toc.html

# Korincanom dobi sumnik
#sed -i 's/Korincanom/Korinčanom/g' $SloKJVepubPath/html/01-toc.html
#sed -i 's/Korincanom/Korinčanom/g' $SloKJVepubPath/html/48-1Cor*.html
#sed -i 's/Korincanom/Korinčanom/g' $SloKJVepubPath/html/49-2Cor*.html

# Galacanom dobi sumnik
#sed -i 's/Galacanom/Galačanom/g' $SloKJVepubPath/html/01-toc.html
#sed -i 's/Galacanom/Galačanom/g' $SloKJVepubPath/html/50-Gal*.html

# Efezanom dobi sumnik
#sed -i 's/Efezanom/Efežanom/g' $SloKJVepubPath/html/01-toc.html
#sed -i 's/Efezanom/Efežanom/g' $SloKJVepubPath/html/51-Eph*.html

# Kolosanom dobi sumnik
#sed -i 's/Kolosanom/Kološanom/g' $SloKJVepubPath/html/01-toc.html
#sed -i 's/Kolosanom/Kološanom/g' $SloKJVepubPath/html/53-Col*.html

# Obe knjigi Tesalonicanom dobita sumnik in Kazalo
#sed -i 's/Tesalonicanom/Tesaloničanom/g' $SloKJVepubPath/html/01-toc.html
#sed -i 's/Tesalonicanom/Tesaloničanom/g' $SloKJVepubPath/html/54-1Thess*.html
#sed -i 's/Tesalonicanom/Tesaloničanom/g' $SloKJVepubPath/html/55-2Thess*.html


# V podrobnem kazalu odstrani naslove poglavij knjig da ostanejo samo stevilke poglavij
sed -i 's/^ <a href=\"\([-a-zA-Z0-9]*\).html\">\([A-Za-zčžšČŽŠ., ]*\) \([0-9]*\)<\/a>/<a href=\"\1.html\">\3<\/a>/g'    $SloKJVepubPath/html/01-toc.html
sed -i 's/Salomonova pesem \[hebr. Pesem pesmi\] \([0-9]\)<\/a>,/\1<\/a>,/g'                                            $SloKJVepubPath/html/01-toc.html


echo "   Kazalo  html/01-toc.html  popravi ..."
echo "      da se da klikati iz Kazala na tocen odlomek v knjigi..."
    # <a href=\"03-Gen-1.html\">1</a>,     
echo "      -1.html   ->   .html#chapter1"
sed -i 's/-\([0-9]*\)\.html/\.html#chapter\1/g'  $SloKJVepubPath/html/01-toc.html
echo "   Kazalo  toc.ncx           popravi ..."
sed -i 's/-\([0-9]*\)\.html/\.html#chapter\1/g'  $SloKJVepubPath/toc.ncx      # |head -50 $SloKJVepubPath/toc.ncx
echo " "

echo "   Popravi posamezne datoteke da linki delujejo."
echo "       <h2>Geneza<br>1. poglavje</h2>   ->    <h2 id=\"chapter2\" >Geneza<br>1. poglavje</h2>"
  for file in *.html; do
    sed -i 's/<h2>\([A-Za-z0-9 ,\xC4\x8C\xC4\x8D\xC5\xA0\xC5\xA1\xC5\xBD\xC5\xBE]*\)<br>\([0-9]*\)/<h2 id=\"chapter\2\" >\1<br>\2/g' "$file"
  done


echo
echo "   Pozene Urejevalnik besedil in v njem pripravi toc.ncx"
echo
gnome-terminal -- sh -c 'gedit /home/pc/Dokumenti/epub/toc.ncx'

echo
echo "   Pozene Sigil 2.0...     zakomentiran"
echo
echo "   Nadaljuj z  Text, desni klik, add existing files "
echo "   iz mape $SloKJVepubPath/html "
echo   
echo "   Potem imas v imenih datotek na vrhu navodila "
echo
#echo "  Ko to koncas to objavi na https://kdp.amazon.com/ "
#echo
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=sigil --file-forwarding com.sigil_ebook.Sigil >/dev/null 2>&1
		# sigil >/dev/null 2>&1    # Ta pozene verzijo 3.0


echo "   Poglejmo ePUB z mupdf bralnikom ..."
# mupdf $SloKJVepubPath/untitled.epub
mv $SloKJVepubPath/untitled.epub $SloKJV_Github/SloKJV.epub


cd $SloKJV_Github

# git add SloKJV.epub
# git commit -m SloKJV - epub Kindle Kobo...

# echo "   Pozene github # zakomentirano"
# github

cd $SloKJVepubPath

# Preveri ali je prav naredil
# pico html/15-1Chr-19.html

# echo "   Odpre brskalnik kjer se knjigo nalozi na Amazon.com"
# xdg-open https://kdp.amazon.com/


echo
echo "   Preveri ePUB "
echo
java -jar /home/pc/Dokumenti/epub/epubcheck-5.1.0/epubcheck.jar  /home/pc/Dokumenti/epub/untitled.epub >log.txt 2>&1
echo
echo "   Pokaze napake v ePUB "
echo
gnome-terminal -- sh -c 'gedit /home/pc/Dokumenti/epub/log.txt'
